### ISSUE TITLE
Doorbel Acdb-6600 (receiving Kaku signal --> homey)

### ISSUE THREAD

**Issue by jaxc0402** [athombv/homey-issues-dp#10]
**What is your Homey version (Settings → System)?**

1.2.0-rc.6

**What did you try to achieve?**

use my (kaku) doorbel

*Please include detailed steps how we can reproduce the issue*

My doorbel is ~7 meters from homey (Acdb-6600) on 1.1.9 no issues. With DP range is to far away.
after restart of 433 microcontroller, ~70 a 75% of the times it works. but not every time

**What was the result?**

homey does not receive signal, and does not respond

**What did you expect as result?**

My homey 'ringing' after doorbell is pressed

**Any other remarks**

battery of button is replaced by a new one.. So not a battery issue

**Comment by jeroenvollenbrock** [comment]
Can you try to create a capture when the button is not working?
Instructions can be found [here](https://github.com/athombv/node-homey-433/blob/master/HOWTO_CREATE_SIGNAL.md).

**Comment by jaxc0402** [comment]
As i already told you via PM (slack name : jaxc) , homey is not receiving anything. Official 'gong' does work even 2 meter further away.

**Comment by jaxc0402** [comment]
So the signal is definitely 'passing' homey. But doesn't get picked up..
