### ISSUE TITLE
[com.athom.homey2] Is the switch On or Off? Both settings have Color!

### ISSUE THREAD

**Issue by Dijker** [athombv/homey-issues-dp#100]
**What is your Homey version (Settings → System)?**
App 0.4.0.104

**What did you try to achieve?**
Switch something on/off

*Please include detailed steps how we can reproduce the issue*
Switching mostly only flips between left and right. 

**What was the result?**
I wonder: Is Left On or Off? Both are colored the same.
(Devices, Auto Update on Apps, etc.)

**What did you expect as result?**
"everywhere" Color = On / Gray = Off like the Switch Settings - Events - Send Call info to Homey. 
only There it works as I expect. 
(I know functionality first..... )

**Comment by joachimroeleveld** [comment]
Will live on here https://github.com/athombv/homey/issues/1875
