### ISSUE TITLE
Mobile app - inclusion instructions only shown when not using templates

### ISSUE THREAD

**Issue by TedTolboom** [athombv/homey-issues-dp#106]
When adding new devices from within the mobile app, the inclusion information is only shown when dedicated html files are used (like with e.g. virtual devices).

Inclusion information from e.g. default Z-wave (Homey > Z-wave) as well as defined Z-wave (e.g. Fibaro Fgd-212) is not shown; white screen

**Comment by joachimroeleveld** [comment]
This should be fixed in the latest release now available for DP. Please reopen if you still encounter issues.

**Comment by TedTolboom** [comment]
@joachimroeleveld still present in latest App release version 1.0 (100) on DP 1.5.6-RC4...

Adding a device with custom Z-wave inclusion instructions shows an empty sheet...
![image](https://user-images.githubusercontent.com/17163431/33683698-15931886-dacc-11e7-88b2-466ed733cfd6.png)

Testing the same device on developers.athom.com shows:
![image](https://user-images.githubusercontent.com/17163431/33683769-556f40b0-dacc-11e7-8bf6-ab5ebdf636a3.png)

In the old interface:
![image](https://user-images.githubusercontent.com/17163431/33683941-d61e35c2-dacc-11e7-8d56-9c7894ddc8be.png)

Let me know if you need further information

**Comment by TedTolboom** [comment]
PS. I don't seem to have an option to re-open this issue

**Comment by joachimroeleveld** [comment]
@WeeJeWel

**Comment by WeeJeWel** [comment]
This should be fixed by now - can you confirm @TedTolboom ?

**Comment by TedTolboom** [comment]
Confirmed to be fixed. Issue can be closed.

**Comment by WeeJeWel** [comment]
Thx!
