### ISSUE TITLE
Mobile app - Android version - Switch toggle stays blue in of mode

### ISSUE THREAD

**Issue by mruiter** [athombv/homey-issues-dp#107]
**What is your Homey version (Settings → System)?**

1.5.3 - Android Alpha Version

**What did you try to achieve?**

Better user experience
**Any other remarks**

The flip switch used when switching of stays blue even if off mode where we would expect a gray version of it just like in the ios version.

![onoff status](https://user-images.githubusercontent.com/17739535/31081062-e104befe-a78a-11e7-82de-b202d7f33f66.png)

**Comment by Dijker** [comment]
Same as #100

**Comment by mruiter** [comment]
Whaha woeps, had to wait a long time to get answer on the picture allowed question :)
