### ISSUE TITLE
[feature request] IOS/desktop - see the flow running

### ISSUE THREAD

**Issue by robiebab** [athombv/homey-issues-dp#110]
**What is your Homey version (Settings → System)?**

IOS/desktop

If you test a flow -> you can see current flow and what paths has been chosen, except you can't click further to see what happens in the next flows.

**Comment by jeroenvollenbrock** [comment]
Can you be a bit more specific?

**Comment by robiebab** [comment]
Example:
Flow 1 -> Flow 2-> Flow 3

flow 1 you can see the card status 
flow 2 not
flow 3 not

For example: if you test flow 1 you can see checkmarks or crosses how the cards went. Except you don't see the status (checkmarks or crosses from the cards) if it runs for example further from flow 1 to flow 2 and what choices it made. you have to go out of the flow and recreate the situation. it would be nice if you have a flow card you can click to the next flow in this case flow 2 and see how it went

**Comment by joachimroeleveld** [comment]
So for my clarity, you would like to be able to see the details of "Run flow x" card during a test?

**Comment by robiebab** [comment]
yes, now you can only test/see the current flow, if you click Test in a flow. i wanna click in a flow on the flow card and go to the next flow, seeing the action from the test that has been executed.

**Comment by WeeJeWel** [comment]
This is very, very complex and therefore won't be added, sorry!
