### ISSUE TITLE
1.5.3 Zigbee add device BUG 

### ISSUE THREAD

**Issue by robiebab** [athombv/homey-issues-dp#114]
**What is your Homey version (Settings → System)?**
1.5.3 

**What did you try to achieve?**
i tryd to add several hue motion sensors(one by one). For some reason it won't work proporley, after adding the second one adding. i get the message already paired. sometimes it works but then i get a dummy, no stats update from that device i didnt even saw that it try to pair. it only works if i remove the battery from all zigbee devices, except for the one that needs to be paired)

*Please include detailed steps how we can reproduce the issue*
Add one zigbee device (philips hue motion sensor i used)
add a second one
get the message already paired or get a dummy device

**What was the result?**
i wasn't able to add a second zigbee device 
or i was and got a dummy device
...

**What did you expect as result?**
i'm able to add multiple zigbee devices without removing theire powersources
...

**Any other remarks**

...

**Comment by jeroenvollenbrock** [comment]
Fixed in 1.5.4-rc.1, can you confirm?
