### ISSUE TITLE
1.5.3 Zigbee remove device BUG #2

### ISSUE THREAD

**Issue by robiebab** [athombv/homey-issues-dp#115]
**What is your Homey version (Settings → System)?**

1.5.3

**What did you try to achieve?**
i try to remove a zigbee device in instellingen -> zigbee -> verwijder apparaat. i set my zigbee device to pairing mode and clicked verwijder apparaat. after a few seconds it stops without any message

*Please include detailed steps how we can reproduce the issue*
set your zigbee device in pairing mode
remove device (instellingen -> zigbee -> verwijder apparaat)
get no message back, button is suddenly availible

**What was the result?**
button to remove device is suddenly availible
...

**What did you expect as result?**
a message that the device wasn't found or is deleted
...

**Any other remarks**
i think it has to do that the device has not be found
...

**Comment by jeroenvollenbrock** [comment]
Fixed in 1.5.4-rc.2

**Comment by robiebab** [comment]
Fixed 👯‍♂️
