### ISSUE TITLE
1.5.4-rc1 zigbee no information from sensors

### ISSUE THREAD

**Issue by robiebab** [athombv/homey-issues-dp#117]
**What is your Homey version (Settings → System)?**

1.5.4-rc1

**What did you try to achieve?**
i'm trying to get new information like lux, temp etc from my zigbee hue sensors

*Please include detailed steps how we can reproduce the issue*
install 1.5.4-rc1 zigbee and it won't work any more. in 1.5.3 it worked

**What was the result?**
the information stays the same on the zigbee devices and wont update
...

**What did you expect as result?**
that the information would update
...

**Any other remarks**
tryd reboot
update the interval time
trigger the zigbee device
...

**Comment by robiebab** [comment]
re-including fixed the problem:

Homey 1.5.4-rc.1
[ZigBee] Moved HA cluster to endpoint 1.

On 1.5.3 HA cluster was linked to endpoint 2; now to endpoint 1...

**Comment by jeroenvollenbrock** [comment]
A re-include should not be required, which kind of device did this occur with?

**Comment by robiebab** [comment]
It is a motion sensor (philips hue motion sensor), the only thing that seemed to worked at that time was motion with a delay. other information like lux and temprature didn't come in. after re-including the devices (4 motion sensors) everything worked fine again. (i can't test it anymore because i re-included them all)

**Comment by kasteleman** [comment]
Found that I made a mistake in the driver I wrote. Did not register the capabilities the right way.
Updated my GitHub repo.

**Comment by RobinBol** [comment]
I will close this issue as it seems to a issue with the Philips Hue ZigBee app.
