### ISSUE TITLE
Homey losing 'connection'

### ISSUE THREAD

**Issue by jaxc0402** [athombv/homey-issues-dp#118]
**What is your Homey version (Settings → System)?**

1.5.0 to 1.5.4-rc1

**What did you try to achieve?**

Keep Homey 'connected' so its reachable from the app
but connection almost every day drops at least one time.
need to PTP to get connection back

*Please include detailed steps how we can reproduce the issue*

Wait until connection drops....

**What was the result?**

Connection keeps dropping

**What did you expect as result?**

Homey to stay alive... and don't lose connection

**Any other remarks**

...

**Comment by jeroenvollenbrock** [comment]
Possibly related to https://github.com/nodejs/node/pull/16489 and https://github.com/nodejs/node/pull/15791

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists in v1.5.5 or not?

**Comment by jaxc0402** [comment]
For me the issue Sems solved. I Yusuf cake back from a 5 dat trip, and Connexion stayed ok. Remote and local
