### ISSUE TITLE
Homey "crashes" / "reboots" couple of times a day.

### ISSUE THREAD

**Issue by DieterKoblenz** [athombv/homey-issues-dp#120]
**What is your Homey version (Settings → System)?**

1.5.4-rc.1

**What did you try to achieve?**

Automatic flows in the morning.

**What was the result?**

During last night I got three announcements from the Candy app that Homey "restarted". At first, I thought this was an error of the app however after looking into the issue it seems Homey does do something weird as my presence state for example is also lost during the night. Uptime is not affected it seems.

**What did you expect as result?**

**Any other remarks**

It started with this version. Never experienced something similar. 

Log of this morning: 500858DE33

**Comment by Dijker** [comment]
Look at your uptime, 
for me it is still counting up but several times a day/night all Apps are restarting due to the GC problem. 
So prpbably no WIFI problem, no OS restarts but Homey Core / all Apps restarting.

**Comment by DieterKoblenz** [comment]
Yeah, Uptime is not affected.

**Comment by jeroenvollenbrock** [comment]
This will be fixed after https://github.com/nodejs/node/pull/16490 lands

**Comment by DieterKoblenz** [comment]
I'll keep an eye on it.. 

No just kidding, if there aren't any "reboots" this night I'll close the issue.

**Comment by DieterKoblenz** [comment]
Thanks Athom! No problems thus far.
