### ISSUE TITLE
Idea IOS app overviewscreen

### ISSUE THREAD

**Issue by robiebab** [athombv/homey-issues-dp#121]
it would be nice if we can see in the overviewscreen if there is motion.
![image-1](https://user-images.githubusercontent.com/18186327/32226366-b7704cfa-be48-11e7-930d-b3459241fb4b.jpg) quick draw example
Normal -> black motion sensor icon
Triggerd -> Red motion sensor icon (flat ui color scheme -> https://flatuicolors.com/img/facebook-share.jpg)

or

On -> light on icon 
Off -> light off icon 
(flat ui color scheme)

or

for the thermostat you can show how hot/cold it is in the icon

**Comment by WeeJeWel** [comment]
Thanks for the suggestion! We will take it under consideration during the design process.

Closing this issue as it cannot be 'solved'.
