### ISSUE TITLE
Mobile App - Firmware update through app

### ISSUE THREAD

**Issue by jeroenbos22** [athombv/homey-issues-dp#122]
**What is your Homey version (Settings → System)?**

1.5.4RC1 / 1.5.4RC2

**What did you try to achieve?**

Update firmware through the iOS app.

**What was the result?**

It did work but was very unclear. It showed a progressbar (which didnt do anything). Right after clicking install update homey went offline. When it got back it showed no update installed (dont know if it was processing the update in the background). Tried to run in again, again nothing happened in the progressbar. Homey went offline for a longer period. When it got back online it was updated

**What did you expect as result?**

A smoother experience ;)

**Comment by joachimroeleveld** [comment]
This should already be fixed in the latest release. Feel free to reopen if you still encounter issues.
