### ISSUE TITLE
setStoreValue / getStoreValue does not correctly serialize date objects

### ISSUE THREAD

**Issue by gruijter** [athombv/homey-issues-dp#123]
**What is your Homey version (Settings → System)?**

1.5.4-rc.1

**What did you try to achieve?**

use the device setStore method to persistently store an object that contains a date object

*Please include detailed steps how we can reproduce the issue*
```
this.device = {};
this.device.lastSeen = new Date();
this.setStoreValue('device', this.device);
this.restoredDevice = this.getStoreValue('device');
>>> restoredDevice.lastSeen: {}
```

**What was the result?**
 the restored value shows an empty object for restoredDevice.lastSeen
...

**What did you expect as result?**

That Date objects are correctly stored to and restored from the store.
...

**Any other remarks**
When first making a string of the date it does get stored/retrieved
```
this.device.lastSeen = new Date().toString();
>>> restoredDevice.lastSeen: 'Tue Oct 31 2017 21:41:02 GMT+0100 (CET)'
```

**Comment by WeeJeWel** [comment]
This has been fixed in the next release!
