### ISSUE TITLE
Geofencing bug

### ISSUE THREAD

**Issue by robiebab** [athombv/homey-issues-dp#124]
**What is your Homey version (Settings → System)?**

1.5.4 rc 2

**What did you try to achieve?**
geofencing doesn’t work correctly after a reboot/ptp; sometimes it works after going outside and in again, sometimes it doesn’t and i have to click into the app (thuisdetectie gebruiken off->on). i would expect that i don’t have to click into the app after a reboot and the homey app retrieves a new status (home/ not home, instead of -. - kills your flows(no status)).

*Please include detailed steps how we can reproduce the issue*
ptp
no status (doesnt occur always)

**What was the result?**
no status home or away
<img width="1143" alt="schermafbeelding 2017-10-31 om 21 23 07" src="https://user-images.githubusercontent.com/18186327/32247166-bd9ffa24-be81-11e7-8f27-d76acabc5c55.png">

...

**What did you expect as result?**
get a status

...

**Any other remarks**

...

**Comment by WeeJeWel** [comment]
Fixed in the next release

**Comment by robiebab** [comment]
After firmware upgrade to RC9 it didn't update the status. my girlfriend was beyond the 200 meters set into the homey app. Homey gave as status she was home

**Comment by jeroenvollenbrock** [comment]
Fixed in rc10

**Comment by robiebab** [comment]
fixed
