### ISSUE TITLE
[AppV2] Cannot delete direct association 

### ISSUE THREAD

**Issue by cbho** [athombv/homey-issues-dp#125]
**What is your Homey version (Settings → System)?**

1.5.4
iOS app v2 1.0.7.4

**What did you try to achieve?**
Delete existing direct association for Fibaro Motion Sensor (group 2) via the app 

*Please include detailed steps how we can reproduce the issue*

**What was the result?**

After deleting the numbers in the fields (making it empty), it is not possible to save changes, thus making it impossible to delete an existing association.

**What did you expect as result?**

...

**Any other remarks**

...

**Comment by joachimroeleveld** [comment]
Is still still the case with the latest version of the app (0.8.3)?

**Comment by cbho** [comment]
Solved in new version.
