### ISSUE TITLE
Driver device settings checkbox gives inverted value

### ISSUE THREAD

**Issue by gruijter** [athombv/homey-issues-dp#126]
**What is your Homey version (Settings → System)?**

1.5.5

**What did you try to achieve?**

make a checkbox in device settings

*Please include detailed steps how we can reproduce the issue*
in app.json:
 ```
{
	"id": "clear_known_devices",
	"type": "checkbox",
	"label": {
		"en": "Delete devicelist",
		"nl": "Apparaatlijst leegmaken"
	},
	"value": false
}
```

in device.js:
```
	onSettings( newSettingsObj, oldSettingsObj, changedKeysArr, callback ) {
		console.log(newSettingsObj); // >> newSettingsObj.clear_known_devices is inverted 
```

**What was the result?**

the reported value for the checkbox is inverted from what is entered in the device settings window
...

**What did you expect as result?**
duh
...

**Any other remarks**

...

**Comment by WeeJeWel** [comment]
You swapped the `oldSettings, newSettings` ;)

**Comment by gruijter** [comment]
Ah, now I have to use a backup of internet to find out from which example I copied the code I used....
