### ISSUE TITLE
IR very unreliable

### ISSUE THREAD

**Issue by DieterKoblenz** [athombv/homey-issues-dp#131]
**What is your Homey version (Settings → System)?**

1.5.6-rc.3

**What did you try to achieve?**

I have flows to change my tuner to CD, Aux or Phono mode. These are learned IC commands but worked correctly before (except for 1.5.4-rc.1)..

**What was the result?**

They only work sometimes, instead of every time.

**What did you expect as result?**

Switching of channel.

**Any other remarks**

...

**Comment by DieterKoblenz** [comment]
Seems to have stopped working completely now.

**Comment by ReinierH** [comment]
Same here. Homey is not sending any IR signals. Tried rebooting Homey without success.

**Comment by jeroenvollenbrock** [comment]
Should be resolved in 1.5.6-rc.4
