### ISSUE TITLE
Zigbee/Kaku not responding 

### ISSUE THREAD

**Issue by Jovink** [athombv/homey-issues-dp#133]
**What is your Homey version (Settings → System)?**

1.5.6rc-3

As title said Zigbee, Kaku not responding
I can't control The ikea lights and the kaku switches won't work either 
Resart the ikea or xiaomi app wont work. 

Z-wave does work i see now.

I can control other things but as milights so it's not frozen completely.

i have made a log 729C6FF393
Made a new log 641E1A6D31

**Comment by denniedegroot** [comment]
I have the same issue, both 433 and zigbee seem to stop responding at the same time. Zwave continues to operate. This happens almost daily.

**Comment by Jovink** [comment]
Problems has been solved after the 1.5.6-rc.4
Case closed 😀
