### ISSUE TITLE
Zone name in device name (improvement)

### ISSUE THREAD

**Issue by DieterKoblenz** [athombv/homey-issues-dp#134]
**What is your Homey version (Settings → System)?**

x.x.x

**What did you try to achieve?**

When you have a device which includes the zone name, zone switching becomes a problem. 

**What was the result?**

For example "Turn on lights in living room" gives a "No lights found" error when you have a device name with the name living room (in it). 

**What did you expect as result?**

**Any other remarks**

This behaviour is annoying and wrong because I want to give sensors a logical name (like PIR living room, Climate Living Room) so I can find them easily in the flow editor. 

There should be a check that excludes non-light devices from this behaviour.

**Comment by WeeJeWel** [comment]
Could you create this (enhancement) issue in the public issue tracker? https://github.com/athombv/homey/issues

Thank you!
