### ISSUE TITLE
Not possible to start brewing coffee with the mobile 2.0 app

### ISSUE THREAD

**Issue by Jovink** [athombv/homey-issues-dp#137]
**What is your Homey version (Settings → System)?**

1.5.6rc-7 

**What did you try to achieve?**
Try to brew coffee with mobile app. 

*Please include detailed steps how we can reproduce the issue*
Select the a mount of coffee. Pressed on the smart coffee icon 

**What was the result?**
Nothing happened 
...

**What did you expect as result?**
I expected a nice cup of coffee 
...

**Any other remarks**
It is also not possible to boil the water with the ikettle. 
I use the Beata of the smarter app.

**Comment by joachimroeleveld** [comment]
Can you explain how you try to do this? Do you try to run a flow? Does it work via the desktop interface? I need a bit more context to be able to help you.

**Comment by Jovink** [comment]
It is not possible to start brewing coffee with the smartphone 2.0 app (android/ios)
With the old app i can press on the icon then it starts brewing.
On the new app it is possible to select the amount of cups but there's no button to start brewing.

**Comment by joachimroeleveld** [comment]
Could you make a screenshot of how this looks on the desktop app?

**Comment by joachimroeleveld** [comment]
Closed as discussed per Slack. (Button will be re-added in new design iteration)
