### ISSUE TITLE
Reusing device flowcard ID's for multiple drivers works different between sdk2 and sdk1

### ISSUE THREAD

**Issue by gruijter** [athombv/homey-issues-dp#138]
**What is your Homey version (Settings → System)?**
1.5.6-rc.7

**What did you try to achieve?**
migrate the enelogic and youless app to sdk2

*Please include detailed steps how we can reproduce the issue*
I have a flowcard with <"id":"tariff_changed">

**What was the result?**
when trying to trigger the card I get an error:
```
{ Error: invalid_device
    at Object.<anonymous> (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:1040)
    at JSON.parse (<anonymous>)
    at Object.jsonToObject (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:938)
    at function.e.apply.s.args.map.s (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1401)
    at Array.map (<anonymous>)
    at HomeyClient._onMessage (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1386)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11) message: 'invalid_device' }
```
...

**What did you expect as result?**
1) To be able to trigger flow cards that have an underscore in its id. Alternatively, If I change the name of the id, existing sdk1 apps will not be able to migrate to sdk2 without losing all the flows.
2) A proper error that would point me where to fix it (took me a day to find out it is caused by the underscore in the card id)
...

**Any other remarks**
Obviously in sdk2 the flow can be triggered if I rename the card in app.json to <"id":"tariffChanged">. But this would break the migration path for sdk1 app users.
...

**Comment by Dijker** [comment]
I feel with you having such errors / problems, 

but I guess it is something else as I upgraded My App from SDK1 to SDK2 while keeping the underscores..

https://github.com/Dijker/nu.dijker.PaperTrails/blob/ace1fea48a9ebf80883cfad5da98638ed18097cd/app.json#L32

Although I have no clue what your error is about. 
Is your code online in an branch available?  
Maybe ask on Slack?

**Comment by gruijter** [comment]
Never mind,

I think the problem was caused by me using the same flow card id for multiple drivers. In app.json I defined the same flowcard for each driver, but then with a different filter. This worked in sdk1. I now changed it to a single definition with a combined filter:
```
      {
        "id":"power_changed",
        "title": {
          "en":"Power use changed",
          "nl":"Stroomverbruik gewijzigd"
        },
        "args": [
          {
            "name": "LS120",
            "type": "device",
            "filter": "driver_id=LS120|LS110",
            "placeholder": {
              "en": "Which device",
              "nl": "Welk apparaat"
             }
          }
        ],
        "tokens":[
```

**Comment by WeeJeWel** [comment]
Yep, that's the way to go. It's undocumented because we still need to do some tests if it's actually the best solution.
