### ISSUE TITLE
Action flow is executed by wrong driver when "sharing" the card definition in app.json

### ISSUE THREAD

**Issue by gruijter** [athombv/homey-issues-dp#139]
**What is your Homey version (Settings → System)?**
1.5.6-rc.7

**What did you try to achieve?**
Define an action card in app.json that works for multiple drivers. In the Enelogic and Youless app I have multiple drivers that need the same action card.

*Please include detailed steps how we can reproduce the issue*
in app.json:
```
			{
				"id": "reboot",
				"title": {
					"en": "Reboot device",
					"nl": "Herstart device"
				},
				"args": [
					{
						"name": "reboot",
						"type": "device",
						"filter": "driver_id=LS120|LS110|LS120S0",
						"placeholder": {
							"en": "Which device",
							"nl": "Welk apparaat"
						 }
					}
				]
			}
```

and in all 3 drivers device.js:
```
			reboot.register()
				.on('run', (args, state, callback) => {
					this.log('reboot of device requested by action flow card');
```

**What was the result?**

When triggering the action from any driver device, the action is always executed by the LS120S0 driver device, also when the action was triggered from an LS120 or LS110 driver device. In above example case this leads to the wrong device being rebooted.
...

**What did you expect as result?**

That the action is executed by the device who's action card is actually used in the flow.
...

**Any other remarks**
I tried checking through args which device triggered the card, but then the execution is stopped after the LS120S0 and never reaches the other drivers anymore...

```
			reboot.register()
				.on('run', (args, state, callback) => {
					if (args.reboot !== this) {
						this.log('nope, this isn\'t mine');
						return callback('not mine');
					}
					this.log('reboot of device requested by action flow card');
```

I also have "shared" trigger and condition cards. I haven't tested with those yet, so there could be issues with that as well
...

**Comment by jeroenvollenbrock** [comment]
Flow cards are not bound to drivers (except by the filter) and should therefore still have only one listener per card. The best solution here is to define a seperate "manager" that binds the listener in which it checks the device type and redirects the event to a specific driver
