### ISSUE TITLE
Auto update not working, manual install gives error

### ISSUE THREAD

**Issue by lubbertkramer** [athombv/homey-issues-dp#14]
**What is your Homey version (Settings → System)?**

1.2 RC6

**What did you try to achieve?**

Apps auto update or manual update because auto update isn't working

**What was the result?**

Auto update is not working, for example the fibaro app is on 1.3.1 and my Homey is on 1.2.3. In the meantime versions 1.2.4, 1.3.0 and 1.3.1 have already been passed. Auto update is on at my Homey. Other users expierence the same problem in dev preview channel.

![fibaro](https://cloud.githubusercontent.com/assets/8224586/23954966/deac23c6-0998-11e7-99a0-776fe2fdf987.PNG)

Manual update results in an error "something went wrong" when after that checking Homey the Fibaro app is updated to 1.3.1

**What did you expect as result?**

That apps auto update without the need of manual update and that the manual update resulted in succes and the app was updated

**Any other remarks**

In dev preview other users report same issue, @m-ruiter found the problem

**Comment by mruiter** [comment]
Confirmed on my homey too with multiple apps that did not update these last days

**Comment by joachimroeleveld** [comment]
Auto updating should work again. I believe the manual installation error is also fixed with it. Please reopen this issue if this is still happening.

**Comment by lubbertkramer** [comment]
Looks like it's still happening, homey on v2.2.1 and in the app store (beta) v2.2.3 - 20.03.17 but no auto update. Also just rebooted and still the old version.

**Comment by WeeJeWel** [comment]
@lubbertkramer what's your Homey's Athom Cloud ID?

**Comment by lubbertkramer** [comment]
Don't know if it's safe to share here, will send by pm on slack :)

**Comment by WeeJeWel** [comment]
Fixed, updates will start coming in during the day again

**Comment by lubbertkramer** [comment]
Neo just got updated, looks like it's solved. Great job!
