### ISSUE TITLE
Qubino dimmer (class socket) not correct working in Alexa skill

### ISSUE THREAD

**Issue by kasteleman** [athombv/homey-issues-dp#140]
**What is your Homey version (Settings → System)?**

1.5.6-rc.8

**What did you try to achieve?**

Use the Qubino dimmer within beta Alexa skill

**What was the result?**

The Dimmer can be turned on and off and even dimmed, but Alexa does not know the status of the dimmer. It never shows a % dim status. Instead after setting the dim value the slider jumps back to zero. It also shows %Power. Could it be that this is related to the class socket that is used for the Qubino dimmer because it also can report power usage and temperature?

**What did you expect as result?**

Dimlevel shown in Alexa

**Any other remarks**

Included is a screen recording from my iPhone. Please rename the file to .MP4 to view the recording!

[ScreenRecording-Alexa Qubino dimmer.zip](https://github.com/athombv/homey-issues-dp/files/1606538/ScreenRecording-Alexa.Qubino.dimmer.zip)

**Comment by WeeJeWel** [comment]
What is the status in the Homey interface of the dimmer?

**Comment by kasteleman** [comment]
In Homey interface the dimmervalue is set to the value previously set
within Alexa. But Alexa reports 0%. If i set the Qubino device to on within
the Homey interface, that is teported back to Alexa, but remains on
dimlevel 0

Op wo 17 jan. 2018 om 17:45 schreef Emile Nijssen <notifications@github.com>

**Comment by WeeJeWel** [comment]
OK Thanks. What'd the Qubino device model?

**Comment by kasteleman** [comment]
HDA2 dimmer

Op do 18 jan. 2018 om 12:39 schreef Emile Nijssen <notifications@github.com>

**Comment by WeeJeWel** [comment]
Fixed!
