### ISSUE TITLE
No Scrollbar at devices

### ISSUE THREAD

**Issue by robiebab** [athombv/homey-issues-dp#141]
**What is your Homey version (Settings → System)?**

1.5.6-rc.8

**What did you try to achieve?**
if you got many devices, you can't scoll down to add an other one (osx app)

*Please include detailed steps how we can reproduce the issue*
-have enough devices that fills the devices screen
- after filling the screen you can't scroll down

**What was the result?**
- after filling the screen you can't scroll down

...

**What did you expect as result?**
there would be a scollbar at devices (osx app)
...

**Any other remarks**

...

**Comment by jeroenvollenbrock** [comment]
We are no longer taking enhancement requests for the desktop interface through this issue tracker, due to it's incoming deprecation. Feel free to make one in the regular issue tracker though.
