### ISSUE TITLE
[cosmetic] Stuff for geeks The Z-Wave tools have been moved to Athom Developer.

### ISSUE THREAD

**Issue by robiebab** [athombv/homey-issues-dp#144]
**What is your Homey version (Settings → System)?**
1.5.6 rc8

my homey language is dutch. If i go to 
 
instellingen ->zigbee
instellingen-> zwave

i see the line:

Stuff for geeks
The Z-Wave tools have been moved to Athom Developer.  

i would expext the following 

(Voorbeeld)
Geavanceerd
De Z-Wave instrumenten zijn verhuisd naar Athom Developer.

**Comment by WeeJeWel** [comment]
We think 'advanced' people understand english :)
