### ISSUE TITLE
[1.5.6.RC9] Homey('s) offline, not reachable by my.athom.com/homey app

### ISSUE THREAD

**Issue by lubbertkramer** [athombv/homey-issues-dp#145]
**What is your Homey version (Settings → System)?**

1.5.6.RC9

**What did you try to achieve?**

 reach Homey at my.athom.com or the Homey app

*Please include detailed steps how we can reproduce the issue*

Homey shows he is offline at my.athom.com /homey app and with the ping to Homey after updating to RC9. Looks like Homey (Zigbee) is working because lights that are in a flow with a doorsensor still react. 

**What was the result?**

Homey offline

**What did you expect as result?**

Homey reachable by my.athom.com and Homey app

**Any other remarks**
Did multiple reboots, a PTP  and a soft reset wich resulted in a RROD (see dp channel)

Ping has the same behaviour as Patrick shared on his screenshot in DP channel:

![homey](https://user-images.githubusercontent.com/8224586/35706331-a9751f76-07a5-11e8-980f-95a87a31fca7.PNG)

**Comment by mruiter** [comment]
also 1 here that went offline. its offsite , managed to do a soft reset when it was going on off on off on off line . did not get a red ring. came online for 15 to 30seconds after that reboot and now stays offline

**Comment by mruiter** [comment]
patrick and robiebab have also same problems

**Comment by PatrickSannes** [comment]
Yep, same issue :(

**Comment by mruiter** [comment]
dijker can also be added to the list

**Comment by robiebab** [comment]
i can also be added to the list, homey is complete unaccesable

**Comment by mruiter** [comment]
Looks like spruttt can be added to the list 2

**Comment by Rido** [comment]
Same issue here. A few hours ago Homey was working fine. 30 minutes ago I wanted to change a flow but Homey was offline. So I pulled the plug out and plugged it back in. But after the orange ring switched off, Homey still appears offline.
After waiting for a while Homey is online again. But this freeze is happening almost every day.. 😭 

Log ID: AE504F6141

**Comment by Dijker** [comment]
Solved for me in rc10

**Comment by lubbertkramer** [comment]
Solved, can be closed
