### ISSUE TITLE
[1.5.6.RC9] athom cloud is not connect

### ISSUE THREAD

**Issue by robiebab** [athombv/homey-issues-dp#147]
**What is your Homey version (Settings → System)?**

[1.5.6.RC9]

**What did you try to achieve?**
i saw that athom cloud is not connected to homey

*Please include detailed steps how we can reproduce the issue*
install rc9 and ptp

**What was the result?**
athom cloud is not connected
...

**What did you expect as result?**
athom cloud is connected
...

**Any other remarks**
i think (assumption) it has to do with ssl (time/date is wrong)
...

**Comment by lubbertkramer** [comment]
+1 as written in my issue #145

**Comment by robiebab** [comment]
fixed
