### ISSUE TITLE
[1.5.6.RC10] Homey freezes on a lot of different apps (Harmony, mysensors..)

### ISSUE THREAD

**Issue by magtimmermans** [athombv/homey-issues-dp#150]
**What is your Homey version (Settings → System)?**

1.5.6.RC10

**What did you try to achieve?**

Connect to homey

*Please include detailed steps how we can reproduce the issue*

Install apps Harmoney, mysensors and use them. My sensors will crash but works great in the 1.5.6RC8 release

**What was the result?**

Homey will freeze and you are not able to connect

**What did you expect as result?**

Not freeze and be repsonsive

**Any other remarks**

No

**Comment by jeroenvollenbrock** [comment]
Could you please follow the contributing guidelines and include a log code?

**Comment by magtimmermans** [comment]
It didn't happen anymore until 1,5 day ago. Is the log still valid if I send it?

**Comment by magtimmermans** [comment]
Seems to be fixed in the last release
