### ISSUE TITLE
[1.5.6.RC9  - RC10] Storage decreasing

### ISSUE THREAD

**Issue by robiebab** [athombv/homey-issues-dp#151]
**What is your Homey version (Settings → System)?**

[1.5.6.RC10]

**What did you try to achieve?**
the storage has been decreasing after RC9. i had before rc9  around 980 mb free of space, after installing rc9 -rc10 it went down to 717 and now 591mb

*Please include detailed steps how we can reproduce the issue*
Install RC9 -RC10 and see that the storage is decreasing

**What was the result?**
i had before rc9  around 980 mb free of space, after installing rc9 -rc10 it went down to 717 and now 591mb
![afbeelding](https://user-images.githubusercontent.com/18186327/35771619-229fa584-0930-11e8-8cc8-1b0983a7b5ae.png)

![afbeelding](https://user-images.githubusercontent.com/18186327/35771617-11e635e6-0930-11e8-9b49-7e3412815f7c.png)

**What did you expect as result?**
around 980mb
...

**Any other remarks**

...

**Comment by jeroenvollenbrock** [comment]
Fixed in rc13
