### ISSUE TITLE
homey 2.0 app and developer tools don't show all apps that have settings

### ISSUE THREAD

**Issue by robiebab** [athombv/homey-issues-dp#152]
**What is your Homey version (Settings → System)?**

1.5.6 RC10, homey app 2.0

**What did you try to achieve?**
i 'm not seeing all the apps the have settings on the developer tools/home2.0 app  

*Please include detailed steps how we can reproduce the issue*
in the app/developer tools i only see the postnl app
<img width="775" alt="schermafbeelding 2018-02-03 om 22 38 22" src="https://user-images.githubusercontent.com/18186327/35771875-e6a5ba4c-0933-11e8-88f5-b91378d5d066.png">

**What was the result?**
i see only the postnl app
...

**What did you expect as result?**
several more apps
better logic
countdown
nest
postnl

<img width="827" alt="schermafbeelding 2018-02-03 om 22 43 05" src="https://user-images.githubusercontent.com/18186327/35771887-1f307136-0934-11e8-9c0e-4267e2f9cb01.png">

...

**Any other remarks**

...

**Comment by Dijker** [comment]
Both the new mobile  app and developer tools only show settings for sdk2 Homey apps. 
This is by design.
Better logic  and countdown are still sdk1 
Postnl is a sdk2 app.

**Comment by SailingDuck** [comment]
What @Dijker  sais. This is the same on my 1.5.3 homey.

**Comment by robiebab** [comment]
if it works by design, i will close the ticket :)
