### ISSUE TITLE
[1.5.7] zwave network graph is diffrent vs network route table

### ISSUE THREAD

**Issue by robiebab** [athombv/homey-issues-dp#162]
**What is your Homey version (Settings → System)?**

1.5.7

**What did you try to achieve?**
i opend https://developer.athom.com/tools/zwave and saw a diffrence between zwave network graph is diffrent and the network route table

*Please include detailed steps how we can reproduce the issue*
open https://developer.athom.com/tools/zwave 
compair the graph with route table

**What was the result?**
it is diffrent
...

**What did you expect as result?**
should be the same

<img width="947" alt="schermafbeelding_2018-03-03_om_00 08 36" src="https://user-images.githubusercontent.com/18186327/36932628-ceb17c34-1ecb-11e8-8c31-ff4214b85afa.png">

...

**Any other remarks**

...

**Comment by WeeJeWel** [comment]
I've removed the chord diagram altogether - it's not very useful.
