### ISSUE TITLE
[1.5.7] Remove device in settings screen (removes other device)

### ISSUE THREAD

**Issue by robiebab** [athombv/homey-issues-dp#163]
**What is your Homey version (Settings → System)?**

1.5.7

**What did you try to achieve?**
i tryd to remove my philips hue remote instead my sensor in the hallway was removed

*Please include detailed steps how we can reproduce the issue*
- go to settings -> zigbee ->remove device
- try to remove a device.
-notice that a diffent device is removed

**What was the result?**
the sensor in the hallway was removed instead of the hue remote
...

**What did you expect as result?**
it would removed the hue remote (leftover unknown device)
...

**Any other remarks**
homey log: 75868B03B1
...

**Comment by RobinBol** [comment]
Settings > ZigBee > Remove device should not be used anymore, it will not be available in the smartphone app. Just use the delete functionality in the devices view.
