### ISSUE TITLE
After adding device renaming does not propagate to flows

### ISSUE THREAD

**Issue by PatrickSannes** [athombv/homey-issues-dp#18]
**What is your Homey version (Settings → System)?**

DP10

**What did you try to achieve?**
Rename the device 

*Please include detailed steps how we can reproduce the issue*

Add device
Rename device
Go to flow editor

**What was the result?**
See the wrong name

**What did you expect as result?**

See the right name

**Any other remarks**

...

**Comment by WeeJeWel** [comment]
This should have been fixed in 1.3
