### ISSUE TITLE
Editing flow with Push Notifications fails loading pick-list of mobile devices

### ISSUE THREAD

**Issue by Dijker** [athombv/homey-issues-dp#19]
**What is your Homey version (Settings → System)?**

1.3.0-rc.1

**What did you try to achieve?**
try re-ordering cards in existing flow.

*Please include detailed steps how we can reproduce the issue*
open flow with 4 action cards, move the 2nd up and save. 

**What was the result?**
pls check your cards for errors.
![image](https://cloud.githubusercontent.com/assets/12412734/25293594/e4a349de-26db-11e7-95f5-045478d4dfbb.png)

**What did you expect as result?**
That it would save.

**Any other remarks**
Save without changing then column works, changing phone or re-ordering makes card invalid and there are no phones available. adding fresh new card send a push notification works OK.

**Comment by Dijker** [comment]
Loading and only changing the phone already fails as the pick-list isn't there....
It works without problem on the 1.2.2 Homey.

**Comment by mruiter** [comment]
can confirm this. seems if you wait long enough on some kind of timeout and get the cloud connect error th list seems to fill

**Comment by Dijker** [comment]
I don't see Cloud connect errors anymore, maybe the bug in the corner is over it....

moving the cards around and/or clearing the device in one card doesn't give an new drop down instantly. 
it can take up to more than a minute to get the devices drop down again (with only 2 devices) 

sometimes it reports an error:
![image](https://cloud.githubusercontent.com/assets/12412734/25355321/814322c6-2936-11e7-80bf-a4a6568e9697.png)

**Comment by WeeJeWel** [comment]
Thanks, both issues fixed!
