### ISSUE TITLE
Flow menu sometimes collapses sometimes keeps open

### ISSUE THREAD

**Issue by mruiter** [athombv/homey-issues-dp#22]
What is your Homey version (Settings → System)? 
1.3.0-rc.1

What did you try to achieve?
When working in my flows i would like to keep the flow folder menu as it is while im working.
So if i have pietje -> puk -> dingen folder open and im creating my flows in there i would like the menu to stay that way. So i can easely create or correct another flow on that level

What was the result?
Sometimes it keeps the folder tree open like it is where i''m working sometimes it collapses to everything closed. I cant find any common way when this happens . Seems random

What did you expect as result?
Keep my folder tree view as is as this is the only normal and workable way if you have many flows and havbe them nicely folderized

**Comment by WeeJeWel** [comment]
This is intended behavior. The menu will:

* Stay open when there's no active Flow
* Auto-hide when a Flow is open, unless the mouse is over the menu

**Comment by WeeJeWel** [comment]
(Of course I'm open for suggestions to improve this behavior)

**Comment by mruiter** [comment]
I will send a picture to make it more clear .I don't mean the whole windows disappearing 




Outlook voor Android downloaden









On Tue, Apr 25, 2017 at 1:46 PM +0200, "Emile Nijssen" <notifications@github.com> wrote:












This is intended behavior. The menu will:

Stay open when there's no active Flow
Auto-hide when a Flow is open, unless the mouse is over the menu

**Comment by Dijker** [comment]
I read Marco's question as if the Tree collapses or keeps open between edits. now after a save it collapses. with duplicate it keeps open. ;-)

**Comment by mruiter** [comment]
Just like dijker said. We want it open as it was when me make flows in our folder in folder in folder in folder tree 




Outlook voor Android downloaden









On Tue, Apr 25, 2017 at 1:51 PM +0200, "Dijker" <notifications@github.com> wrote:












I read Marco's question as if the Tree collapses or keeps open between edits. now after a save it collapses. with duplicate it keeps open. ;-)

**Comment by WeeJeWel** [comment]
Oh, folders are collapsing?

Could you update your screenshots? They're not visible.

**Comment by mruiter** [comment]
![how it always comes back after editting or making a flow](https://cloud.githubusercontent.com/assets/17739535/25386310/41cd701a-29c7-11e7-8a1b-defeb14bb8fa.JPG)
![how i want it to stay](https://cloud.githubusercontent.com/assets/17739535/25386311/41f66dc6-29c7-11e7-9ef7-87f761f551f0.JPG)

**Comment by WeeJeWel** [comment]
Fixed!

**Comment by mruiter** [comment]
Love you




Outlook voor Android downloaden









On Tue, Apr 25, 2017 at 3:04 PM +0200, "Emile Nijssen" <notifications@github.com> wrote:












Fixed!
