### ISSUE TITLE
1.3 Alarms missing features and cards

### ISSUE THREAD

**Issue by lubbertkramer** [athombv/homey-issues-dp#24]
**What is your Homey version (Settings → System)?**

1.3RC2

**What did you try to achieve?**

Use alarms in other columns to change the alarm or use the alarm as an and statement. For example in the software update was stated that it would be possible to change the alarm when an appointment would be canceled. 

Software update 31-3
Flows where you automatically wake up later when that calendar appointment is cancelled are now possible! Or wake up a little bit earlier so you won't get rained at work.

***What am i missing***

Cards or features of alarms

And column:
- Alarm(s) or specific alarm goes of earlier then x time
- Alarm(s) or specific alarm goes of later then x time
- Alarm(s) or specific alarm goes of between or not between two times
- Alarm(s) or specific alarm goes of on x date
- Alarm(s) or specific alarm goes of on a day, weekday or weekendday

Then column:
- Update or set Alarm(s) or specific alarm
- Change Alarm(s) or specific alarm to other day
- Change Alarm(s) or specific alarm x minutes/hours earlier or later
- Change Alarm(s) or specific alarm to other time

**What was the result?**
Not possible

**What did you expect as result?**

more cards to use in flows

**Any other remarks**

**Comment by Tweake** [comment]
We will not be implementing all of those due to various practical reasons which we discussed at the community event. However, these cards will also be added in rc4:

![screen shot 2017-05-01 at 17 02 32](https://cloud.githubusercontent.com/assets/10051731/25582953/07e01524-2e90-11e7-83de-eaf871393023.png)

**Comment by jeroenvollenbrock** [comment]
Fixed in 1.3.0-rc.8.

**Comment by lubbertkramer** [comment]
Not fully agree on closing this one because not all features are added from the issue. I understand why but it's been told alarms would work like above and it's also a wish that it will be working that way
