### ISSUE TITLE
1.3 Insights picker is ugly/out of view

### ISSUE THREAD

**Issue by lubbertkramer** [athombv/homey-issues-dp#25]
**What is your Homey version (Settings → System)?**

1.3RC2

**What did you try to achieve?**

Select a date range at insights. Same issue in the browser as in the homey desktop app.

**What was the result?**
1.3
![13](https://cloud.githubusercontent.com/assets/8224586/25358114/9e107552-2940-11e7-9ef7-0e865f4235f7.PNG)

Other Homey on 1.2
![12](https://cloud.githubusercontent.com/assets/8224586/25358119/a259feee-2940-11e7-9d84-b86d5326205b.PNG)

**What did you expect as result?**
Something like 1.2

**Comment by Dijker** [comment]
Confirmed! 
And not only ugly......  it doesn't work in Chrome ;-)

**Comment by WeeJeWel** [comment]
Fixed!

**Comment by Dijker** [comment]
Confirmed, Fixed! The old one is back? 
and imho works like a charm.....

Nice !! System - Memory and Load !!
