### ISSUE TITLE
Flow cards unresponsive using desktop app

### ISSUE THREAD

**Issue by swttt** [athombv/homey-issues-dp#26]
**What is your Homey version (Settings → System)?**

1.3.0-rc3

**What did you try to achieve?**

Switch cards

**What was the result?**

Nothing happened
**What did you expect as result?**

Cards switching

**Any other remarks**

Refresh fixes everything

**Comment by WeeJeWel** [comment]
Do you mean cycling through cards within a column? E.g. pressing the up/down arrows.

**Comment by swttt** [comment]
Indeed, noticed it happens after switching then between columns. Then they seem unresponsive.

**Comment by WeeJeWel** [comment]
Should be fixed by now.
