### ISSUE TITLE
Trashcan reminder app voice input is not working anymore

### ISSUE THREAD

**Issue by rhannink** [athombv/homey-issues-dp#27]
**What is your Homey version (Settings → System)?**

1.3.0-rc.3

**What did you try to achieve?**

Ask Trashcan reminder when the blue trashcan is being fetched

*Please include detailed steps how we can reproduce the issue*

I ask in Dutch: " wanneer wordt de blauwe container opgehaald" or "Op welke dag wordt de blauwe container opgehaald"

**What was the result?**

Homey outputs: "Ik kan geen geldige wekker vinden"

**What did you expect as result?**

Homey outputting: "De blauwe container wordt as maandag opgehaald"

**Any other remarks**

Seems like with the introduction of alarms in 1.3.0, new reserved keywords are introduced, these keywords where used by the trashcan reminder app before this release.........

**Comment by Tweake** [comment]
Fixed in rc4

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?

**Comment by rhannink** [comment]
This problem was indeed solved in RC4. Trashcan reminder works as before....
