### ISSUE TITLE
Unable to install app with invalid 433 signals

### ISSUE THREAD

**Issue by gruijter** [athombv/homey-issues-dp#28]
See https://github.com/athombv/homey/issues/1507#issuecomment-298292488

**What is your Homey version (Settings → System)?**

x.x.x

**What did you try to achieve?**

*Please include detailed steps how we can reproduce the issue*

**What was the result?**

...

**What did you expect as result?**

...

**Any other remarks**

...https://github.com/athombv/homey/issues/1507#issuecomment-298292488

**Comment by jeroenvollenbrock** [comment]
This should now be resolved.
