### ISSUE TITLE
When speaker switches forcibly the original speaker get's an pause command

### ISSUE THREAD

**Issue by BasKiers** [athombv/homey-issues-dp#3]
**What is your Homey version (Settings → System)?**
1.2.0

**What did you try to achieve?**
Have Sonos as Homey Music speaker playing a song and then put it in pause state. After that play a playlist from the sonos app (overwriting the song from Homey Music). 

**What was the result?**
This will cause the sonos to receive a pause command from Homey.

**What did you expect as result?**
Sonos should keep playing the overwritten playlist

**Any other remarks**

**Comment by TheMSB** [comment]
Should be fixed in the next update 👍
