### ISSUE TITLE
Alarms cards resize on number (Scrollbar missing)

### ISSUE THREAD

**Issue by Dijker** [athombv/homey-issues-dp#30]
**What is your Homey version (Settings → System)?**
1.3.0.-rc6
on Samsung Tablet, phone (S7 Egde) but result on all devices the same 

**What did you try to achieve?**
Add multiple alarms from phone/tablet 

*Please include detailed steps how we can reproduce the issue*
Add/edit/view multiple alarms 

**What was the result?**
3 or 4 alarms size well,  adding the 4th and more alarms they are sized to fit the screen ;-) 

![image](https://cloud.githubusercontent.com/assets/12412734/25968428/bc314526-3691-11e7-9798-5b4351d2613c.png)

**What did you expect as result?**
that it fits with a scrollbar ;-)

**Comment by WeeJeWel** [comment]
Haha whoops, fixed

**Comment by jeroenvollenbrock** [comment]
Fixed in 1.3.0-rc.8
