### ISSUE TITLE
Wekker ging af op een niet ingestelde dag. 

### ISSUE THREAD

**Issue by Jovink** [athombv/homey-issues-dp#31]
**What is your Homey version (Settings → System)?**

1.3.0 RC7

**What did you try to achieve?**
Alarm has be set for everyday except the weekend

*Please include detailed steps how we can reproduce the issue*
Set the alarm for everyday except the weekend. Make sure the alarm is active

**What was the result?**
The alarm goes on in the weekend on a horrible time.

**What did you expect as result?**
That I could sleep for a few hours, and only the alarm goes on on a weekday

**Any other remarks**
However I have made a flow for the alarm the alarm sound on homey did work too

**Comment by Dijker** [comment]
Confirmed, 
Created an Alarm for Tue + Saturday, 
Created a Flow -> Log 
Test, working Correct!
Removed Saturday  (today) and set for new time in 1 or 2 minutes from now.

Unexpected, Again it triggers!

**Comment by Tweake** [comment]
Thanks for reporting the issue, it will be fixed with the next build

**Comment by jeroenvollenbrock** [comment]
Fixed in 1.3.0-rc.8
