### ISSUE TITLE
app crash with'No stack trace available' and exit signal:SIGKILL

### ISSUE THREAD

**Issue by gruijter** [athombv/homey-issues-dp#34]
**What is your Homey version (Settings → System)?**

1.3.0 - rc7

**What did you try to achieve?**

*Please include detailed steps how we can reproduce the issue*

Just install a number of apps and let it run for a while. Although memory usage seems ok, Homey starts shutting down apps after a while with exit signal SIGKILL

**What was the result?**

...

**What did you expect as result?**

...

**Any other remarks**

It seems related to certain apps being installed, although I'm not sure about that. One app is Magister, and another that seems to trigger it is TV Gids. The apps themselves show a normal memory usage.

0AB90D6D14 (Note: TV gids was installed, Magister was not installed when this log was created) 

see also:
https://github.com/athombv/homey/issues/1147

and:
https://github.com/athombv/homey/issues/1548

**Comment by jeroenvollenbrock** [comment]
Your log shows out of memory issues

**Comment by gruijter** [comment]
I am sure it is related to https://github.com/athombv/homey/issues/1573#issuecomment-304533449

Any news on solving this long lasting memory problem? That apps are just being shut down, even when memory usage seems normal for apps, is very frustrating. It makes Homey an unreliable home automation platform :(  Can you please take your time to thorougly investigate and solve this once and for all ? 👍

**Comment by jeroenvollenbrock** [comment]
rc 10 contained a fix for a possible memory leak in HomeyOS. We've so far used both static code analysis tools, runtime analysis and crash report analysis, and did not find any more memory leaks, so i'm hopeful that this one has been resolved now. If it still happens, it is most likely related to just having too many apps running simultaneously.

**Comment by gruijter** [comment]
Ok, testing already 😎. Fingers crossed 🤞
