### ISSUE TITLE
1.3.0 rc8 - Invalid nodess - Zwave devices going invalid

### ISSUE THREAD

**Issue by mruiter** [athombv/homey-issues-dp#36]
**What is your Homey version (Settings → System)?**

1.3.0 rc8

**What did you try to achieve?**

A working zwave enviroment

**What was the result?**

Devices going invalid / invalid node

**What did you expect as result?**

Stability

**Any other remarks**
log send in under number 
4E16DA3AFE

as of now already 4 devices have gone to invalid node status. they seem to follow the sequence they where added

**Comment by jeroenvollenbrock** [comment]
Your log shows settings corruption, i think this is related to #37 Gonna close this for now as that one is resolved in rc11
