### ISSUE TITLE
1.3.0 rc8 - No more devices - Flows all corrupt - But superfast Homey ;)

### ISSUE THREAD

**Issue by mruiter** [athombv/homey-issues-dp#37]
**What is your Homey version (Settings → System)?**

1.3.0 rc8

**What did you try to achieve?**

See a device in devices that where there before the first reboot on RC8

**What was the result?**

No more devices available . 3 New added Zwave devices . 1 dissapeared also 2 are invalid  

**What did you expect as result?**

Devices

**Any other remarks**

See log ID : 82AD82B250

**Comment by jeroenvollenbrock** [comment]
Fixed in rc11
