### ISSUE TITLE
Music trough headphones and internal speaker

### ISSUE THREAD

**Issue by Jovink** [athombv/homey-issues-dp#4]
**What is your Homey version (Settings → System)?**

1.2.0 rc.1
When playing Soundcloud trough headphones the homey speaker played music too

**Comment by TheMSB** [comment]
Hey thank you for reporting the issue! Is the problem reproducible? and if so could you detail in steps how you got to the state where audio was playing through both the Homey speaker and the headphones at the same time?

**Comment by TheMSB** [comment]
@Jovink This issue should be resolved with patch 1.2.0-rc.3. I will close the issue for now but please let us know if this issue continues to be a problem for you.
