### ISSUE TITLE
Adding IKEA Trådfri devices duplicates the added device on Homey.

### ISSUE THREAD

**Issue by Dijker** [athombv/homey-issues-dp#40]
**What is your Homey version (Settings → System)?**
1.4.0-Alpha 2
**What did you try to achieve?**
Add IKEA bulbs or rotating dimmer
*Please include detailed steps how we can reproduce the issue*
Sideloaded the app on DP Homey
Add Bulb from menu, toggle the bulp on-off 6x 
Wait...

**What was the result?**
I see the Bulb added 2 times in Homey, not in the ZigBee Network Graph. 
Switching the one on/off or color temp. changes the status of the second also.

**What did you expect as result?**
Adding one bulb.

**Any other remarks**
After removing it bothe where removed! and adding it again it worked OK. 

Also happend for other IKEA Bulbs and the rotating Dimmer.

**Comment by TedTolboom** [comment]
confirmed also for other non-Ikea devices

**Comment by swttt** [comment]
Yup, tried to add a 2nd osram light...took a few resets etc. but instead of adding it once...it added 20 times 😀

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?
