### ISSUE TITLE
Homey is unreachable for installing from App Store

### ISSUE THREAD

**Issue by Dijker** [athombv/homey-issues-dp#41]
**What is your Homey version (Settings → System)?**
1.4.0-alpha 2 

**What did you try to achieve?**
Install an app from the store.

*Please include detailed steps how we can reproduce the issue*
As usual, 
Checked Homey itself - settings. everything OK
No "could not connect to the cloud" msg on settings page!

but still "Homey is unreachable Try again" from the App store. 
2nd time today with this Homey DP 1.4.0 alpha 2, other Homey (1.3.2) still normal functioning.
1st time just rebooted Homey to solve the incident, 2nd time today I send Log before restart: C8D01E8E02 

**What was the result?**
Restarted Homey and after Restart no problem.... 2nd log: 710A12A27E 

**What did you expect as result?**
working the first time ;-)

**Comment by Dijker** [comment]
Happende again this morning,  everything working fine except no installation possible form App Store.

**Comment by jeroenvollenbrock** [comment]
Should be resolved in alpha 3

**Comment by Dijker** [comment]
Didn't happen again after update .....
