### ISSUE TITLE
Preview of Voices doesn't work 

### ISSUE THREAD

**Issue by Dijker** [athombv/homey-issues-dp#42]
**What is your Homey version (Settings → System)?**
1.4.0.- alpha 2 

**What did you try to achieve?**
test other Voice 

*Please include detailed steps how we can reproduce the issue*
Go to: Settings - Voice 
Pres one of the test buttons.

**What was the result?**
Silence.....

**What did you expect as result?**
Hallo Ik ben Homey or Hi I am Homey 

**Any other remarks**

**Comment by DieterKoblenz** [comment]
No issues here with Homey Firmware Versie: 1.4.0-alpha.2 all the test buttons give "Hi, I am Homey"

**Comment by Dijker** [comment]
ok, Thanks, 
Testing it with changing the speed did work, but removing (uniinstall) Amy? doesn't give the option to install (download ) her or other voices again ?!???!!
![image](https://user-images.githubusercontent.com/12412734/27285087-b94167be-54fb-11e7-94f5-8a6da784b595.png)


Maybe already corruption from before 1.3.x ?

**Comment by Dijker** [comment]
This one solved itself by changing language to Dutch (then it worked already) and back to English! 
I can download all including the beautiful  Indian Raveena ;-)

I see it as an incident maybe coming from pre 1.3.0 corruptions ?

**Comment by jeroenvollenbrock** [comment]
That is indeed most likely
