### ISSUE TITLE
[1.4.0-alpha.3] Zigbee devices are to the home zone instead of the chosen (TEST) zone

### ISSUE THREAD

**Issue by TedTolboom** [athombv/homey-issues-dp#44]
**What is your Homey version (Settings → System)?**

1.4.0-alpha.3

**What did you try to achieve?**

Add Xiaomi Zigbee devices to Homey in the TEST zone

**What was the result?**

Zigbee device is added (in duplicate) to the Home (root) zone instead
![image](https://user-images.githubusercontent.com/17163431/27371317-9c1e0f32-5660-11e7-9598-2fc15f365ee8.png)

**What did you expect as result?**

Device added in the TEST zone, similar to the Z-wave and other devices

**Any other remarks**

LOG: EA571E460D

**Comment by swttt** [comment]
Confirm it happens to Osram as well

**Comment by RobinBol** [comment]
Thanks for reporting, this is fixed!
