### ISSUE TITLE
Sleeping card not working

### ISSUE THREAD

**Issue by jaxc0402** [athombv/homey-issues-dp#45]
**What is your Homey version (Settings → System)?**

1.4.0 alfa3

**What did you try to achieve?**

To use the flow card 'sombody is sleeping'

*Please include detailed steps how we can reproduce the issue*

I made a flow ' the sun goes down' AND 'nobody is sleeping' THEN close all sunscreens

**What was the result?**

The flow always triggers, also if somebody is sleeping, I activated somebody sleeping tru voice on homey, and by fone with the mobile app.

**What did you expect as result?**

Sunscreens NOT going down when somebody is asleep

**Any other remarks**

...

**Comment by WeeJeWel** [comment]
Hm, the translation is a bit lousy. The card actually is 'When everyone is awake', and inverted, when that is false.

You might have a user which's sleep state is unknown, which explains this behavior.
