### ISSUE TITLE
[1.4.0-alpha.3] Zigbee remove device from devices "please wait until Zigbee is ready" > removed

### ISSUE THREAD

**Issue by TedTolboom** [athombv/homey-issues-dp#46]
**What is your Homey version (Settings → System)?**
1.4.0-alpha.3

**What did you try to achieve?**
Remove a Zigbee device from devices window

**What was the result?**
Remove a device window is show, with message "please wait until Zigbee is ready" 
<img width="665" alt="schermafbeelding 2017-06-21 om 20 50 05" src="https://user-images.githubusercontent.com/17163431/27404792-a114cc46-56cf-11e7-8dd9-eb10ccc11981.png">

and after some time, without waking the device, the devices (incl. duplicates) are removed and window closes

**What did you expect as result?**
message to wake-up the device / confirm removal (user intervention)

**Any other remarks**
LOG: 8B7D8CA305

**Comment by TedTolboom** [comment]
For an device which is offline, the following window is shown:
<img width="590" alt="schermafbeelding 2017-06-21 om 22 28 44" src="https://user-images.githubusercontent.com/17163431/27405229-0958220c-56d1-11e7-8a7d-f0f0ecd303e6.png">
and devices are removed without interaction

**Comment by RobinBol** [comment]
Thanks for reporting, should be fixed: https://github.com/athombv/homey-client/commit/8a97a6f3c4902556de42af04d4175b1250ad3aa0
