### ISSUE TITLE
[1.4.0-alpha.3] Zigbee remove device from Zigbee settings > missing instructions > timeout

### ISSUE THREAD

**Issue by TedTolboom** [athombv/homey-issues-dp#47]
**What is your Homey version (Settings → System)?**
1.4.0-alpha.3

**What did you try to achieve?**
Remove a Zigbee device from Zigbee Settings, click node, click remove

**What was the result?**
Nothing is shown, after some time (10s = 10000ms), timeout is shown:
<img width="351" alt="schermafbeelding 2017-06-21 om 23 07 41" src="https://user-images.githubusercontent.com/17163431/27406973-f778abc8-56d6-11e7-846e-919f6d3a6aae.png">

If I wakeup the device after pressing the remove button, the device is removed

**Comment by RobinBol** [comment]
Thanks for reporting, should be fixed: https://github.com/athombv/homey-client/commit/1e1a8ebd0d01056e212ae30fbb88455aae35c16c
