### ISSUE TITLE
[1.4.0-alpha.3] Inclusion of Xiaomi sensors fails or cluster indentification is incomplete

### ISSUE THREAD

**Issue by TedTolboom** [athombv/homey-issues-dp#48]
**What is your Homey version (Settings → System)?**
1.4.0-alpha.3

**What did you try to achieve?**
Inclusion of Xiaomi Zigbee sensors to Homey based on app and driver (https://github.com/TedTolboom/com.xiaomi-mi-zigbee) defined by information of other home automation platforms

**What was the result?**
The temperature sensor is able to be included. But will show broken as invalid_cluster_undefined.
<img width="270" alt="schermafbeelding 2017-06-21 om 23 27 34" src="https://user-images.githubusercontent.com/17163431/27407586-390b74ba-56d9-11e7-8bb9-fc259ea394a7.png">

Logging as shown on the CLI will show node as undefined and only basic clusters identified and not the device specific ones:
```
[debug] Node: undefined
[debug] - Endpoint: 0
[debug] -- Clusters:
[debug] --- genBasic
[debug] ---- cid :  genBasic
[debug] ---- sid :  attrs
[debug] --- genIdentify
[debug] ---- cid :  genIdentify
[debug] ---- sid :  attrs
[debug] --- genGroups
[debug] ---- cid :  genGroups
[debug] ---- sid :  attrs
[debug] --- genScenes
[debug] ---- cid :  genScenes
[debug] ---- sid :  attrs
[debug] --- genMultistateInput
[debug] ---- cid :  genMultistateInput
[debug] ---- sid :  attrs
[debug] --- genOta
[debug] ---- cid :  genOta
[debug] ---- sid :  attrs
[debug] --- manuSpecificCluster
[debug] ---- cid :  manuSpecificCluster
[debug] ---- sid :  attrs
[debug] - Endpoint: 1
[debug] -- Clusters:
[debug] --- genIdentify
[debug] ---- cid :  genIdentify
[debug] ---- sid :  attrs
[debug] --- genGroups
[debug] ---- cid :  genGroups
[debug] ---- sid :  attrs
[debug] --- genScenes
[debug] ---- cid :  genScenes
[debug] ---- sid :  attrs
[debug] --- genMultistateInput
[debug] ---- cid :  genMultistateInput
[debug] ---- sid :  attrs
[debug] - Endpoint: 2
[debug] -- Clusters:
[debug] --- genIdentify
[debug] ---- cid :  genIdentify
[debug] ---- sid :  attrs
[debug] --- genGroups
[debug] ---- cid :  genGroups
[debug] ---- sid :  attrs
[debug] --- genScenes
[debug] ---- cid :  genScenes
[debug] ---- sid :  attrs
[debug] --- genAnalogInput
[debug] ---- cid :  genAnalogInput
[debug] ---- sid :  attrs
```
The driver already includes the `msTemperatureMeasurement` and `msRelativeHumidity` clusters which are required for this device but not validated during inclusion.

Remaining devices (button, motion sensor and door sensor) show the following error message:
<img width="591" alt="schermafbeelding 2017-06-21 om 21 52 54" src="https://user-images.githubusercontent.com/17163431/27407627-70e9c224-56d9-11e7-911d-9d4ca5130ee1.png">

**What did you expect as result?**
Smooth inclusion

**Any other remarks**
LOG: 8B7D8CA305

**Comment by jeroenvollenbrock** [comment]
The xiaomi zigbee devices are not fully zigbee compliant, and support will require a few 'hacks' arround that. I'm closing this issue for now, but feel free to open an enhancement request in the regular issue tracker.
