### ISSUE TITLE
[1.4.0-alpha.3] Device driver debugging impossible without Zigbee logging / ability to send RAW commands

### ISSUE THREAD

**Issue by TedTolboom** [athombv/homey-issues-dp#49]
**What is your Homey version (Settings → System)?**
1.4.0-alpha.3

**What did you try to achieve?**
Inclusion of Xiaomi Zigbee sensors to Homey based on app and driver (https://github.com/TedTolboom/com.xiaomi-mi-zigbee) defined by information of other home automation platforms

**What was the result?**
Inclusion of these sensors failed or was incomplete, see #48
No additional logging available to determine the cause of the failures.

**Any other remarks**
Please add similar Zigbee logging and or add ability to send RAW commands as is currently available for Z-wave

**Comment by jeroenvollenbrock** [comment]
This is actually an enhancement request that does not have a high priority right now. I'm closing this issue, but feel free to open an enhancement request in the regular issue tracker.
