### ISSUE TITLE
Zone control no longer works by speech

### ISSUE THREAD

**Issue by DieterKoblenz** [athombv/homey-issues-dp#5]
**What is your Homey version (Settings → System)?**

1.2.0-rc2

**What did you try to achieve?**

"Zet het licht uit in de woonkamer"

**What was the result?**

"Ik kon geen lampen vinden om uit te zetten." / No lights turned off.

**What did you expect as result?**

Lights off in the living room ;)

**Any other remarks**

Controlling individual lights now works, but zones are broken.

**Comment by Tweake** [comment]
I'm not able to reproduce this yet. Could you please add a screenshot showing your zones and the devices in the zone named _woonkamer_? It would be great if you could also add the brand names of each of the lights in the _woonkamer_.

**Comment by DieterKoblenz** [comment]
![image](https://cloud.githubusercontent.com/assets/2961896/23516878/d164576c-ff6e-11e6-9bd2-32df46c6d36b.png)

**Comment by Tweake** [comment]
Could you send me a message on Slack so we can exchange some more specifics about the issue? I'm `@robert`
