### ISSUE TITLE
[OSRAM] Can't add 3rd RGB bulb

### ISSUE THREAD

**Issue by swttt** [athombv/homey-issues-dp#50]
**What is your Homey version (Settings → System)?**

1.4.0-alpha.3

**What did you try to achieve?**

Add Osram lightly device.
Did reset them a few times.

**What was the result?**

The last (3rd) light doesn't wants to get added. Did noticed it shows in the graph, but not in devices.

**What did you expect as result?**

The lights get added to devices.

**Any other remarks**

I am not 100% sure, but after i added the 2nd light i switched it to the living room zone. The first time i added the 3rd device the 2nd one was back in the home zone. Switched it back to the living room, since then i am not able to add the 3rd device.

Kinda feels like 2 id's are hiding behind 1 device card or something (not even sure if thats possible)

**Comment by swttt** [comment]
Removed the 2nd device again. (wasn't able to remove the device from the geeks graph)
Now was able to add both devices again, so got all 3 of them paired now 😀

Was thinking this trough, but maybe (might have had a brainfart) when i added the 3rd device i named it exactly the same as the already added 2nd one and moved it to the same zone.

**Comment by jeroenvollenbrock** [comment]
Are you sure this is not due to #44?

**Comment by swttt** [comment]
100% sure... checked every zone. It was visible in the graph. After i deleted the 2nd device it worked. And was able to add the 2nd again and the 3rd.

**Comment by swttt** [comment]
Got some ghosting devices again.

This time in a totally different way (so not sure if i should open a new issue or not)
After you guys updated/downgraded the Lightify app and removed the zigbee drivers, i removed the old one and installed the new beta.

Now i was unable to add the lights back in expect for one (my guess is i did click the cross on the device card for this one), but the other two don't want to get paired again.

BUT they do show up in the graph as online and don't have a device card. Resetting the bulbs didn't work as expected, still unable to add them.

**Comment by RobinBol** [comment]
Have you tries removing them from the network graph?

**Comment by swttt** [comment]
Not yet, haven't thought about that one...since it wasn't working in alpha1.

Will try :)

**Comment by swttt** [comment]
Log: A46F9E40D4

**Comment by jeroenvollenbrock** [comment]
Has this been resolved in rc6/7?

**Comment by RobinBol** [comment]
Since this issue has been inactive for a while, and I did not receive any complaints related to this issue I will close it. If This issue is somehow not solved, please let us know.
