### ISSUE TITLE
[1.4.0-alpha.3] node information missing on device card & filter button in Zigbee settings

### ISSUE THREAD

**Issue by TedTolboom** [athombv/homey-issues-dp#51]
**What is your Homey version (Settings → System)?**
1.4.0-alpha.3

**What was the result?**
1) Zigbee settings 'filter' button, don't think filter is the right word (device ID's?), on developers.athom.com it is referred to as </>. Keep / make consistent.

2) Node information, e.g. device ID's and provided names / basic clusters, are missing on the device cards at devices. I would expect that node info is also available at the device card; similar to Z-wave Node information

**Comment by RobinBol** [comment]
Thanks for reporting, I agree that filter is rather strange. I changed the device information window in the network graph to directly show the necessary information (generating it was not really needed). Further, I added device settings for zigbee devices (like z-wave) to show the information there as well. Updated the docs where needed.
