### ISSUE TITLE
[Zigbee] Delete device not working properly

### ISSUE THREAD

**Issue by caseda** [athombv/homey-issues-dp#53]
**What is your Homey version (Settings → System)?**
1.4 alpha 3

**What did you try to achieve?**
Delete a device from within the zigbee settings, which succeeds according to the message, but does not remove the device from homey, it only "unpairs" the device, setting it offline in the mesh, and leaving it in homey devices.
Now marked offline i can't delete it anymore, as that results in `removeNode.Timed out after 10000 ms`.
Deleting the device from the device page, does delete the device, but lets the device remain in the zigbee settings (mesh overview) making them permanent there.

**Please include detailed steps how we can reproduce the issue**
Remove a device from the zigbee setting's mesh overview, by clicking on the device, then pressing the "remove" button.
See it turn offline after a refresh of the overview. (rest is explained above)

**What did you expect as result?**
That the device is deleted from homey completely, including from the mesh overview and devices page

**Any other remarks**
offline devices keep existing, even on restart of the zigbee network (so it's not a reset i guess?) and a reboot of homey

**Comment by RobinBol** [comment]
Thanks for reporting, this is fixed!
