### ISSUE TITLE
[1.4.0-alpha.3][Bug] homey presence

### ISSUE THREAD

**Issue by robiebab** [athombv/homey-issues-dp#54]
**What is your Homey version (Settings → System)?**

1.4.0 alpha 3

**What did you try to achieve?**
homey getting my location to set me home or away

*Please include detailed steps how we can reproduce the issue*
-reboot homey 
-reboot homey by ptp

**What was the result?**
homey can't find the location
...

**What did you expect as result?**
homey can't find the location
...

**Any other remarks**

...

**Comment by jeroenvollenbrock** [comment]
@robiebab I'm not completely understanding this issue, can you elaborate a bit more?

**Comment by robiebab** [comment]
for some reason if i reboot my homey (normal way or ptp), homey can't get my location from the app. after disable and enable "use home detection" it is most works most of the cases. if i ptp that change is 50% or lower

**Comment by robiebab** [comment]
also on ios 11 beta homey presence won't work anymore, i'm using smart presence for the moment

**Comment by WeeJeWel** [comment]
Please note that the app only sets your location when it changes. So after rebooting Homey, it does not ask your phone for the location.

**Comment by robiebab** [comment]
the problem now is that the app or homey doesn't give the location after a reboot. it only response when i disable and enable "use home detection"  in the homey app. in IOS 11 home presence won't work at all. so i don't know why we are closing this ticket
