### ISSUE TITLE
[1.5.0-alpha.2]->[bug] [1.5.0-alpha.5] memory bug

### ISSUE THREAD

**Issue by robiebab** [athombv/homey-issues-dp#55]
**What is your Homey version (Settings → System)?**

1.4.0 alpha 3

**What did you try to achieve?**
homey has some memory issues

*Please include detailed steps how we can reproduce the issue*

**What was the result?**
some apps act slow after swapping
...

**What did you expect as result?**
i don't expect homey to have a memory bug
<img width="1144" alt="schermafbeelding 2017-06-18 om 16 19 53" src="https://user-images.githubusercontent.com/18186327/27508225-d174d594-58e0-11e7-8265-496d1c36ef0c.png">

...

**Any other remarks**

...

**Comment by jeroenvollenbrock** [comment]
@robiebab I don't see any problems in that screenshot, can you elaborate a bit more on the issue a hand?

**Comment by robiebab** [comment]
The problem is that since 1.4.0 alpha, my homey is swapping. 
**Memory**: 
homey
system 


Those two where far less high i had around 100mb free of memory and now 12 mb including swapping

**Comment by robiebab** [comment]
<img width="836" alt="schermafbeelding 2017-07-05 om 23 03 11" src="https://user-images.githubusercontent.com/18186327/27884913-44736fe4-61d6-11e7-90ff-8977452fbf8b.png">

**Comment by jeroenvollenbrock** [comment]
Does this issue persist in 1.5.0-alpha.1+?

**Comment by robiebab** [comment]
it still persist on 1.5.0-alpha.1  i only have 22 mb left

**Comment by robiebab** [comment]
it also shows minues 23,88 mb system memory

<img width="979" alt="schermafbeelding 2017-07-16 om 11 08 19" src="https://user-images.githubusercontent.com/18186327/28247529-ad8afb8c-6a32-11e7-8f68-b8c7a16f1eab.png">
