### ISSUE TITLE
[1.4.0-alpha.3] Z-wave error creating socket during device removal initiated from devices

### ISSUE THREAD

**Issue by TedTolboom** [athombv/homey-issues-dp#56]
**What is your Homey version (Settings → System)?**
1.4.0-alpha.3

**What did you try to achieve?**
Removal of a Z-wave device initiated from the devices section.

**What was the result?**
The following error message was shown repeatedly:
<img width="594" alt="schermafbeelding 2017-06-25 om 11 29 17" src="https://user-images.githubusercontent.com/17163431/27515194-6b96aac2-599e-11e7-895f-f1feae39e12b.png">

If error is closed, blank window is shown, but nothing happens (also not after time out):
<img width="606" alt="schermafbeelding 2017-06-25 om 12 00 19" src="https://user-images.githubusercontent.com/17163431/27515197-71427370-599e-11e7-9642-68b58b6d28b6.png">

Checked for multiple devices (different apps and drivers); consistently the same error.

Initiating remove a node from Z-wave settings, does show the "Please put your Z-Wave device in learn mode..."

Rebooting Homey - same issue
PTP Homey (30 sec) - same issue => unable to remove a Z-wave device from Devices section

**Any other remarks**
LOG: B61E533251 before reboot
LOG: B844E8402A after PTP

**Comment by jeroenvollenbrock** [comment]
Should be resolved in rc6/7, can you confirm?

**Comment by WeeJeWel** [comment]
Probably :)
