### ISSUE TITLE
measure_water capability has incomplete functionality

### ISSUE THREAD

**Issue by gruijter** [athombv/homey-issues-dp#57]
**What is your Homey version (Settings → System)?**

1.4.0-alpha.3

**What did you try to achieve?**

use the measure_water capability in an app

*Please include detailed steps how we can reproduce the issue*
in app.json added:
```
"class": "sensor",
      "capabilities": [
        "measure_water",
        "meter_water"
			]
```

**What was the result?**
meter_water works as expected. But measure water
* is lacking an icon in the device card
* does not provide a trigger flow card
...

**What did you expect as result?**

an icon and a trigger flow card

**Any other remarks**

...

**Comment by WeeJeWel** [comment]
Fixed
