### ISSUE TITLE
[1.4.0-alpha.3] Homey announces to start recovery and cancels it without any trigger or action

### ISSUE THREAD

**Issue by TedTolboom** [athombv/homey-issues-dp#58]
**What is your Homey version (Settings → System)?**
1.4.0-alpha.3

**What did you try to achieve?**
Gentle waking up... enjoying my cup of coffee...

**What was the result?**
all of the sudden Homey speaks up "starting recovery", "recovery cancelled" without any triggers / action from my side

**Any other remarks**
LOG: E64B5E0504

**Comment by jeroenvollenbrock** [comment]
Should be fixed

**Comment by zshh** [comment]
Mine just did this 5 minutes ago. Stable 1.5.3 version. Any ideas?
