### ISSUE TITLE
[1.4.0-alpha.3]-> [1.5.0-RC3] sensor gives false motion after reboot

### ISSUE THREAD

**Issue by robiebab** [athombv/homey-issues-dp#59]
**What is your Homey version (Settings → System)?**

1.4.0 alpha.3

**What did you try to achieve?**
after a reboot  some sensors got triggerd on motion without a reseason
FIBARO motion sensor node 94
FIBARO motion sensor node 46

(if i walk by and retrigger the motion sensor then it go's well again)

*Please include detailed steps how we can reproduce the issue*
reboot homey 
within a hour homey gives false readings on the fibaro motion sensor

**What was the result?**
the lights went on without a reason
...

**What did you expect as result?**
motion sensor only triggers on motion
...

**Any other remarks**
systemlog: 3CF3F5EEA5
...

**Comment by WeeJeWel** [comment]
Could you please elaborate what false readings are in this scenario?

**Comment by WeeJeWel** [comment]
And ideally find out if this is a Homey issue or a Fibaro App issue.

**Comment by robiebab** [comment]
i think it is a homey issue because it always happens when i reboot, and sometimes out of the ordinary. the false readings are that the sensor senses motion. The sensor keeps that status until i walk by and homey get's a new status from the sensor.

**Comment by robiebab** [comment]
Reboot :13:29

2017-07-16 13:32.05 sensor van de Gang gaat zonder reden na herstart zeggen dat er beweging is
2017-07-16 13:36.03 sensor van de WC gaat zonder reden na herstart zeggen dat er beweging is

zie bijlage:

[Untitled.txt](https://github.com/athombv/homey-issues-dp/files/1150977/Untitled.txt)

**Comment by robiebab** [comment]
still active in 1.5.0-alpha.5

**Comment by robiebab** [comment]
still active in 1.5.0-RC3

**Comment by jeroenvollenbrock** [comment]
Should be resolved in RC6, can you confirm?

**Comment by robiebab** [comment]
still active on 1.5.0

**Comment by jeroenvollenbrock** [comment]
Should be resolved _after_ installing 1.5.6-rc3.

**Comment by jeroenvollenbrock** [comment]
Closed to combine under athombv/homey#2267
