### ISSUE TITLE
[1.5.0-alpha.1] Links to App store on Settings / Apps dont work 

### ISSUE THREAD

**Issue by Dijker** [athombv/homey-issues-dp#60]
**What is your Homey version (Settings → System)?**
1.5.0-alpha.1

**What did you try to achieve?**
Install Can I wear shorts today?
App Store links Top and each App don't work, although the Bug Report Link Works!!

**What was the result?**
On Homey Desktop App 1.0.2 and 1.0.3 on Windows, 
 Same on Latest Chrome ;-) (tested first!)

**What did you expect as result?**
Start Chrome with an App Store tab

**Comment by WeeJeWel** [comment]
Fixed
