### ISSUE TITLE
[1.5.0-alpha.1] notification update report can't be clicked away

### ISSUE THREAD

**Issue by robiebab** [athombv/homey-issues-dp#61]
**What is your Homey version (Settings → System)?**

[1.5.0-alpha.1]

**What did you try to achieve?**
trying to click away the message that homey has been updated

*Please include detailed steps how we can reproduce the issue*
update homey to [1.5.0-alpha.1]
get notification that it has been updated in the to left corner
click cross to read it
message is gone
go to other tab and message is back

**What was the result?**
notification din't go away
...

**What did you expect as result?**
notification go away
...

**Any other remarks**

...

**Comment by lubbertkramer** [comment]
+1, keeps coming back

**Comment by mruiter** [comment]
Confirm , same here

**Comment by WeeJeWel** [comment]
Fixed

**Comment by robiebab** [comment]
there are still issues: sometimes after a reboot you'll get old messages that already been removed. and sometimes the just reappear again

**Comment by WeeJeWel** [comment]
Does this still happen in 1.5.0-alpha.3?

**Comment by robiebab** [comment]
yes the notification messages that i clicked away yesterday have been returned
