### ISSUE TITLE
[1.5.0-alpha-1] Zigbee crash on boot

### ISSUE THREAD

**Issue by swttt** [athombv/homey-issues-dp#63]
**What is your Homey version (Settings → System)?**

1.5.0-alpha1

**What did you try to achieve?**

Updated to 1.5.0.

**What was the result?**

After it's done booting zigbee isn't working.

**Any other remarks**

During boot the LED ring hangs orange for a while (not moving)

**Comment by lubbertkramer** [comment]
Same here:

> ZigBee Instellingen
> ZigBee is aan het laden, een moment...

**Comment by mruiter** [comment]
Confirm, same here

**Comment by Dijker** [comment]
Same here....

**Comment by jeroenvollenbrock** [comment]
Can you guys please send me some log id's after booting without zigbee coming up?

**Comment by swttt** [comment]
8DD102FB13

**Comment by Dijker** [comment]
2B5FBE7EA5

**Comment by mruiter** [comment]
alpha 4 still has broken zigbee

**Comment by mruiter** [comment]
log file on alpha 4 

36464B1966

**Comment by lubbertkramer** [comment]
Alpha 3 working zigbee alpha 4 zigbee keeps loading -> C6B130B86B

**Comment by TedTolboom** [comment]
Same here:
Alpha 2, Zigbee keeps loading
Alpha 3, working
Alpha 4, Zigbee keeps loading
Log: DE469566D1
