### ISSUE TITLE
Homey.get in settings frontend not working anymore after upgrade to fw 1.5

### ISSUE THREAD

**Issue by gruijter** [athombv/homey-issues-dp#64]
**What is your Homey version (Settings → System)?**

 1.5.0-alpha.2

**What did you try to achieve?**

Use Homey.get() in the frontend to get settings of an app

*Please include detailed steps how we can reproduce the issue*

The app was already installed and running (Magister beta 2.0.3). After the upgrade from 1.4 to 1.5 it is not possible to add a new student from the settings screen. 

**What was the result?**

It appears that Homey.get() as used in settings.js of the Magister app is not returning a settings value or error anymore when using it to get all settings:
 ```
Homey.get(function(err, settings) {
if(err) return console.error('Could not get all settings', err);
    allStudents=settings;
})
```
**What did you expect as result?**

That the apps continues to work the same as before the firmware upgrade

**Any other remarks**

```Homey.get('', function(err, settings) { ```
fixes it (notice the added '', as first argument)

**Comment by WeeJeWel** [comment]
Fixed
