### ISSUE TITLE
[1.5.0-alpha-2] No session during setup after recovery

### ISSUE THREAD

**Issue by lubbertkramer** [athombv/homey-issues-dp#65]
**What is your Homey version (Settings → System)?**

[1.5.0-alpha-2]

**What did you try to achieve?**

Do a full recovery because of issue https://github.com/athombv/homey-issues-dp/issues/62, that worked now but when running setup at the end got this message, Homey did started and boot up

*Please include detailed steps how we can reproduce the issue*

Followed the steps at setup.athom.com and after downloading voice for a good conversation got this message

**What was the result?**

no session

**What did you expect as result?**

no problems 

**Any other remarks**

Log 78B010D779 (clean Homey after new setup)

![nosession](https://user-images.githubusercontent.com/8224586/28192200-d2338b2a-6834-11e7-9390-1f5dad19bfe0.PNG)

**Comment by WeeJeWel** [comment]
Does this still occur? I've pushed a fix last week.
