### ISSUE TITLE
[1.5.0-alpha-2] Homey not ready

### ISSUE THREAD

**Issue by lubbertkramer** [athombv/homey-issues-dp#66]
**What is your Homey version (Settings → System)?**

[1.5.0-alpha-2] 

**What did you try to achieve?**

After testing the recovery because of issue https://github.com/athombv/homey-issues-dp/issues/62 i got an error during setup as noted in this issue https://github.com/athombv/homey-issues-dp/issues/65 Homey did boot up but when going to the device page i get the message "not ready" and i don't see my Homey icon

Edit:
Did 3 factory resets to test if the error would resolve

**What was the result?**

Got the not ready error and don't see my Homey at the device page

**What did you expect as result?**

Seeing Homey at the device page after clean recovery

**Any other remarks**

Log 78B010D779 (clean Homey after new setup)
...
![not ready](https://user-images.githubusercontent.com/8224586/28192209-dd85599a-6834-11e7-88eb-ba2c8ae3b56e.PNG)

**Comment by WeeJeWel** [comment]
Fixed
