### ISSUE TITLE
[1.5.0-alpha-2] True OR (True AND Confrmation) timed-out with False...

### ISSUE THREAD

**Issue by Dijker** [athombv/homey-issues-dp#67]
**What is your Homey version (Settings → System)?**

1.5.0-alpha-2

**What did you try to achieve?**
Test the OR Scenario
![image](https://user-images.githubusercontent.com/12412734/28229274-5dbe5c1c-68e2-11e7-9820-ac3b3e3a2251.png)

*Please include detailed steps how we can reproduce the issue*
Having a True Condition Group1 with some true condition in Group2 with an confirmation timed out on getting no confirmation.

**What was the result?**
No Action on evaluating True || (True && Confirm) after the timeout of the confirmation.
Delayed action after negative confirmation True || (True && NotConfirmed) 
(VRAAG het me dan niet !!!! ;-) ) 

**What did you expect as result?**
Direct action and no confirmation (Speech or Mobile) as the answer is already known when one of the groups is true.

**Any other remarks**
Nice work the OR !!!

**Comment by WeeJeWel** [comment]
FIxed

**Comment by Dijker** [comment]
Confirmed Fixed!
