### ISSUE TITLE
[Flow] Device card -> alarm on/off missing translation

### ISSUE THREAD

**Issue by swttt** [athombv/homey-issues-dp#69]
**What is your Homey version (Settings → System)?**

1.5.0-alpha3

**What did you try to achieve?**

Missing translation on the device cards alarm on and the card alarm off.
Homey is set in English here, but cards still in Dutch.

<img width="255" alt="schermafbeelding 2017-07-17 om 19 45 21" src="https://user-images.githubusercontent.com/17660608/28281887-d862819e-6b28-11e7-923d-c9a927dd35e3.png">

**Comment by WeeJeWel** [comment]
Fixed
