### ISSUE TITLE
Music shows ', undefined' behind artist

### ISSUE THREAD

**Issue by swttt** [athombv/homey-issues-dp#7]
**What is your Homey version (Settings → System)?**

1.2.0RC3

**What was the result?**
Using google music as a service displays undefined in the UI, just behind the artist name (e.g. Adele, Undefined) .
Happens on multiple artists.

**What did you expect as result?**

Like the example given above it should have only displayed 'Adele'

**Any other remarks**
Doesn't happen on all artists! Seems random to me, don't know.

Screenshot
<img width="213" alt="schermafbeelding 2017-03-04 om 22 12 11" src="https://cloud.githubusercontent.com/assets/17660608/23582360/ab027ade-0128-11e7-983b-5bfd00653436.png">

**Comment by TheMSB** [comment]
Should be fixed
