### ISSUE TITLE
Devicecard for class 'other' is not providing capabilities view

### ISSUE THREAD

**Issue by gruijter** [athombv/homey-issues-dp#70]
**What is your Homey version (Settings → System)?**

1.5.0-alpha.3

**What did you try to achieve?**

make an app with a device class 'other' with custom capabilities

*Please include detailed steps how we can reproduce the issue*

app.json:

```
"capabilities": {
			"InternetConnectionStatus": {
					"type": "boolean",
					"title": {
							"en": "Internet Connected"
					},
					"getable": true,
					"setable": false
			},
			"DownloadSpeed": {
					"type": "number",
					"title": {
							"en": "Download speed"
					},
					"getable": true,
					"setable": false,
					"units": {
							"en": "MB/s"
					}, etc etc

"drivers": [
      "class": "other",
      "capabilities": [ "InternetConnectionStatus", "DownloadSpeed", "UploadSpeed", "AttachedDevices" ],
```

**What was the result?**

The devicecard (in the browser) only has the settings link, but not the capabilities link

After changing the class to 'sensor' I did get the capabilities link on the devicecard

**What did you expect as result?**

That class 'other' provides the same functionality as class 'sensor' on the devicecard

**Any other remarks**

...

**Comment by WeeJeWel** [comment]
This is expected behavior. When using class `other` you're expected to add your own `mobile` property.

P.S Please follow capability naming standard (lowercase, underscore), not Windows conventions ;)

**Comment by gruijter** [comment]
Ok, uderstood. Maybe the documentation can be updated on this topic. :)

**Comment by WeeJeWel** [comment]
Good one, I've added it :)
