### ISSUE TITLE
Voice Settings current Voices missing

### ISSUE THREAD

**Issue by Dijker** [athombv/homey-issues-dp#71]
**What is your Homey version (Settings → System)?**

1.5.0-alpha.3

**What did you try to achieve?**
Check Voices

*Please include detailed steps how we can reproduce the issue*
Go to Settings - Voice

**What was the result?**
![image](https://user-images.githubusercontent.com/12412734/28316079-8d29a15a-6bc1-11e7-8a51-c73f1e9835f7.png)

**What did you expect as result?**
somthing like 
![image](https://user-images.githubusercontent.com/12412734/28316149-e8ce2724-6bc1-11e7-972c-0bda36242169.png)

The current Voices between Voice and Also installed....

**Any other remarks**
Settings maybe corrupt? 
Switching Eng - Dutch  and back didn't fix

Log: 92DA440FF8

**Comment by WeeJeWel** [comment]
Fixed in next release, thx!
