### ISSUE TITLE
[1.5.0-alpha.4] Change in Then-Else behavior on inconclusive_response

### ISSUE THREAD

**Issue by Dijker** [athombv/homey-issues-dp#72]
**What is your Homey version (Settings → System)?**

1.5.0-alpha.4

**What did you try to achieve?**
Test OR ;-)

*Please include detailed steps how we can reproduce the issue*
![image](https://user-images.githubusercontent.com/12412734/28437673-d3bfc79e-6d9b-11e7-9f6d-a477a556cd56.png)

**What was the result?**
Before on an 
- Confirm => Execute Then
- Deny => Execute Else
- inconclusive_response => Nothing!

**What did you expect as result?**
On above screenshot Nothing!
But Homey now executed Else !!
(this was different before!)

**Any other remarks**
Is this intended change in behavior?  
I liked the original behavior!

**Comment by Dijker** [comment]
So to compare Raspberry's with Raspberry's as we say, 
or to compare Homeys Flows with Homeys Flows, only other difference is The language. ;-)

Now on 1.3.2 (Dutch)
![image](https://user-images.githubusercontent.com/12412734/28439086-c08b3cbc-6da0-11e7-958c-08b3fbc3414d.png)

Now on 1.5.0.alpha.4 (English) 
![image](https://user-images.githubusercontent.com/12412734/28439293-908b6716-6da1-11e7-813d-d90a4e14405d.png)

**Comment by WeeJeWel** [comment]
Fixed!
