### ISSUE TITLE
[1.5.0-alpha4] Devices all on/off flow card not checking null values

### ISSUE THREAD

**Issue by swttt** [athombv/homey-issues-dp#73]
**What is your Homey version (Settings → System)?**

1.5.0-alpha4

**What did you try to achieve?**

After a countdown is 0 i check if there are any lights on in the livingroom, using the new device condition card. (device all on/off in a zone)

**What was the result?**

Despite all the device being off and some being undefined/null by a non function zigbee, it still thinks some lights are on. I am guessing this happens because of the `null` values for some devices.

**What did you expect as result?**

That it checks for `null` , and expecs those to be off as well.

**Any other remarks**

...

**Comment by WeeJeWel** [comment]
Fixed
