### ISSUE TITLE
[1.5.0-alpha-5] ->[1.5.0-RC3]  Bug in Or & ElseFlow

### ISSUE THREAD

**Issue by robiebab** [athombv/homey-issues-dp#75]
**What is your Homey version (Settings → System)?**
1.5.0-alpha-5

**What did you try to achieve?**
i tryed to add a card to a existing flow in the or/else colum.

result
i can't add the card to an existingflow in the or/else colum

expected result:
i can add the card to an existingflow in the or/else colum

see video
https://athomcommunity.slack.com/files/robiebab/F6FF79C6P/naamloos.mov

**Comment by robiebab** [comment]
still active in [1.5.0-RC3]

**Comment by cscottmcqueen** [comment]
I have noticed this too.  Works fine when creating a new flow but sometimes when you go back to edit the flow it will not let you add new cards into the columns bottom section, instead the card jumps to the top section of the column.

You can resolve by closing the program and reopening but sometimes it takes a few times and as it is completely random it is incredibly frustrating
