### ISSUE TITLE
1.5.0-alpha-7 memory usage doesn't add up 

### ISSUE THREAD

**Issue by robiebab** [athombv/homey-issues-dp#82]
**What is your Homey version (Settings → System)?**

1.5.0-alpha-7

**What did you try to achieve?**
checking the memory bar for inconsistency

*Please include detailed steps how we can reproduce the issue*
if you count for every app the memory place, you get a diffrent outcome

**What was the result?**
i got less memory then displayed on the bar
...

**What did you expect as result?**
it should be the same
...

**Any other remarks**

...

**Comment by jeroenvollenbrock** [comment]
Caused by #83
