### ISSUE TITLE
 1.5.0-alpha-7 memory (system app)

### ISSUE THREAD

**Issue by robiebab** [athombv/homey-issues-dp#83]
**What is your Homey version (Settings → System)?**

 1.5.0-alpha-7 

**What did you try to achieve?**
system(app) still got a minus sign wich let them homey think there is more memory 
 
<img width="843" alt="schermafbeelding 2017-08-01 om 19 57 53" src="https://user-images.githubusercontent.com/18186327/28839787-12dfed34-76f5-11e7-9dc4-7f2bd455d3a1.png">

**Comment by jeroenvollenbrock** [comment]
Apps can share cache when the same items are cached. If this is the case, the bars of both apps show this shared cache, and system corrects for it. if system usage is less then the combined shared cache corrections, it drops into the negative values. I’ve been thinking of a way to show this in a more logical manner, but i’m not that fond of applying magic scalars or something to the app usage
