### ISSUE TITLE
1.5.0-RC2 Homey Cloud connection fails often

### ISSUE THREAD

**Issue by scanno** [athombv/homey-issues-dp#85]
**What is your Homey version (Settings → System)?**

1.5.0-RC.2

**What did you try to achieve?**
The connection to the homey cloud is very often not available. The homey Android app can't make a connection to my homey from the mobile network. Also the owntracks location messages are not received by the homey owntracks app. 

On the internal network homey is accessible (and also with a VPN connection from the mobile network). 

After a reboot of homey, the cloud is available, but after a while it's gone again. Using MQTT for receive owntracks location messages is working fine. Also using the local ip address of homey for owntracks location messages is working as it should. 

Seems like problems started around alpha 7 (but that is just a guess). On earlier alpha versions, homey cloud was working fine. 

Started fiddling with the Ikea zigbee devices around the same time (just trying to be complete, could well be irrelevant)

**Comment by jeroenvollenbrock** [comment]
This should be resolved in rc6, can you confirm?

**Comment by scanno** [comment]
Seems good so far.
