### ISSUE TITLE
1.5.0-RC-3 - would you like to save this flow [ bug]

### ISSUE THREAD

**Issue by robiebab** [athombv/homey-issues-dp#86]
**What is your Homey version (Settings → System)?**

1.5.0-RC-3

**What did you try to achieve?**
opening a flow 

*Please include detailed steps how we can reproduce the issue*
open a few flows an then you get the message would you like to save
![afbeelding](https://user-images.githubusercontent.com/18186327/28994866-d214de0e-79d8-11e7-9a68-3ee39a3bbe8d.png)

**What was the result?**
you get a message would uou like to save this flow
...

**What did you expect as result?**
if i did not make any changes i would not get this message
...

**Any other remarks**

...

**Comment by WeeJeWel** [comment]
Is the Flow broken by any chance?

**Comment by robiebab** [comment]
Homey gives that answer if you scroll trough your existing flows that work

**Comment by robiebab** [comment]
here is an example: https://ufile.io/laikw

**Comment by Dijker** [comment]
I see this still in the final 1.5.0, 
even for new flows created after upgrade to 1.5.0
Expected something like upgrade of old flows to new format with OR and Then but don't see the link when it happens and when not.

**Comment by Dijker** [comment]
@WeeJeWel 
Did you already find something?
See it here many times, with old and new flows. but not consequent sometimes it happens but opening a flow where it happend has no problem when I open that flow directly (Reload Browser)
Seen on both Homey's 
What I see: Most of the time after viewing a second or later flow: 

Open a flow (first complete load)
Navigate to open second flow. only view
Load other flow or navigate away << repeat until it happens!

At this point in the console activeFlowJson is "{}" where it  should contain the original flow JSON  for what I see.

**Comment by WeeJeWel** [comment]
This issue will not be fixed because it takes a lot of time, and our focus is on the Homey Smartphone App for now. So I'm closing the issue, thank you for reporting anyway!
