### ISSUE TITLE
SDK2 In-App time uses zulu time instead of current timezone, resulting in a -2 hours difference

### ISSUE THREAD

**Issue by scanno** [athombv/homey-issues-dp#87]
**What is your Homey version (Settings → System)?**

2.5.0-RC4

**What did you try to achieve?**

The owntracks app uses date/time stamps for creating a small in memory log that can be shown to users to see what is going on with the owntracks app. 
This date/timestamp was displaying the correct date/time on SDK1. Since i have rewritten the app to use SDK2, there is a 2 hour difference in the time displayed in the loglines and the current time taking into account the timezone and daylight saving.

**What did you expect as result?**
I would have expected the date/time displayed in the loglines to match the current date/time and not a 2 hour difference.

**Comment by jeroenvollenbrock** [comment]
Fixed in rc5
