### ISSUE TITLE
Z-Wave network thats build from start on 1.5.x series does not seem to mesh

### ISSUE THREAD

**Issue by mruiter** [athombv/homey-issues-dp#88]
**What is your Homey version (Settings → System)?**
1.5.0-rc6 atm started on the early rc's already

**What did you try to achieve?**

I'm trying to let my z-wave network mesh. I have two houses at this site.
House 1 Has plugs , Garden in between has a plug, guest house 15 meters away from homey has plugs.
Also tested it with a lineup of 6 plugs al 5 meters appart all connected directly to homey and did not mesh on themselfs , (tried fibaro and neo)
All connected directly to homey and so the last plugs in this lineup did not function. Also re-pair on that position did not do anything , so pairing in mesh also not functional

**What was the result?**

Screenshot
![knipsel](https://user-images.githubusercontent.com/17739535/29398608-d8880f8a-8325-11e7-8913-b8be38d84ecb.PNG)

**What did you expect as result?**

Z-wave building up a mesh network as it should to improve distance and stability

**Any other remarks**

MarkSwift also started clean on 1.5 and also has this problem. 
There now have been 4 other people next to mark and myself reporting on slack with the same problem.

1 thing Mark and I have in common is the setting corruption bug that made us start over on these 2 homeys. The other users on slack just started with there homey so updated from store to experimental and started on 1.5 also. 1 of them has enough zwave knowledge and 40+ devices that do not mesh.

Ohh, 1 other thing Mark and i have in common are the 18+ sideloaded apps ;)

The z-wave network is not large i know. But thats because the devices i tried to add do not function / react without mesh when i put them into there function places.

**Comment by mruiter** [comment]
Screenshot from user razorfish79
Started on 1.3 now on 1.5 added a lot of devices . Fibaro plugs for instance and cant get them to mesh

![screenshot_20170817-083716](https://user-images.githubusercontent.com/17739535/29399183-73d9c242-8328-11e7-8b49-df06b51148ba.jpg)

**Comment by Swiftnesses** [comment]
Not too many devices working with Homey today as the mesh issue was killing me... This is what I have right now.

<img width="553" alt="screen shot 2017-08-17 at 08 30 45" src="https://user-images.githubusercontent.com/1001877/29400787-7872b914-8326-11e7-9995-c8980749df8f.png">

**Comment by Keverjeroen** [comment]
I'm not sure if this is related, but maybe it helps. All devices are Z-wave plus, except Nr 2, the Fibaro plug. Alle devices where added to the network before version 1.5, and were all added in close distance from Homey (and moved later).

I have 3 powered Z-wave devices (+ Homey):
- Ground: Nr 1 + 19
- 2nd floor: Nr 18
- 3rd floor: Nr 2

The strange thing is that some battery devices connect to the most distant plug (Nr 2 / zolder). Like Nr 15, the doorsensor of the front door, downstairs. That sensor is very close to plug Nr 19, a bit further from Nr 1 Homey, even further from plug Nr 18 and realy far from plug Nr 2.

Plug Nr 18 is very close to smoke sensor 21 (+/- 3 meters) and directly 1 floor under plug 2. But Nr 18 isn't meshing.

Plug Nr 19 is close to Homey (+/- 3 meters), close to both door sensors (15 and 22) and close to the multi sensor (14). But Nr 19 isn't meshing.

![zwave-map](https://user-images.githubusercontent.com/18548628/29402168-4653d0a4-8334-11e7-9129-b7b6269a7cd5.png)

**Comment by Inversion-NL** [comment]
A bit the same for me: although I got the feeling the network graph isn't the correct representation of the action Z-wave routing.

Device 38 is on the ground floor and is mains powered and thus is routing.
However device 51 is also mains powered and isn't routing. (N.b. this device is being disconnected every few weeks, don't know if that matters)

What however amazes me the most: If I interpret the layout correctly is that it looks like the 'rookmelders' on the bg, first and second floor are routing. That's not possible since they are battery powered.
What's missing is the link from device 38 directly to Homey: then the map would be correct.

Another thing I noticed while looking at my map: device 48 and 54 aren't connected to Homey at all. Since device 54 is offline that would/could make sense however device 48 is still reporting

![image](https://user-images.githubusercontent.com/15921016/29406235-be598e3e-8340-11e7-8072-add29c92db35.png)

**Comment by bvdbos** [comment]
@Inversion-NL 38 and 1 are routing so the "Rookmelders" connect to both these routing nodes.

**Comment by Inversion-NL** [comment]
Yes but node 38 and 51 aren't directly connected to Homey, only through the 'rookmelders'.
Which couldn't be the case because they aren't routing nodes.

**Comment by jeroenvollenbrock** [comment]
Fixed in rc7
