### ISSUE TITLE
Possibility to remove unknown devices from zwave

### ISSUE THREAD

**Issue by robiebab** [athombv/homey-issues-dp#89]
**What is your Homey version (Settings → System)?**

1.5.0 RC6

it is not possible to manualy/automaticaly remove unknown devices from homey
<img width="886" alt="schermafbeelding 2017-08-18 om 01 29 02" src="https://user-images.githubusercontent.com/18186327/29438119-f28f86a8-83b4-11e7-9951-9c736bf47a2f.png">

**Comment by bvdbos** [comment]
For Zigbee this works really nice in rc6 now.

**Comment by jeroenvollenbrock** [comment]
This is actually an enhancement request that does not have a high priority right now. I'm closing this issue, but feel free to open an enhancement request in the regular issue tracker.
