### ISSUE TITLE
Reset ZigBee Network possible without confirmation

### ISSUE THREAD

**Issue by Dijker** [athombv/homey-issues-dp#90]
**What is your Homey version (Settings → System)?**

1.5.0.rc7

**What did you try to achieve?**
test the reset Zigbee button.

*Please include detailed steps how we can reproduce the issue*
Klick

**What was the result?**
Like you expect on Linux ;-) 
It worked, Zigbee network of Homey is clean.

**What did you expect as result?**
A confirmation like Reset Z-wave.... 
(I am a Windows user, Are you sure? )

**Any other remarks**
Needed a Reset anyway ;-)

**Comment by RobinBol** [comment]
Hm good idea:p will add it

**Comment by RobinBol** [comment]
Added it, thanks for the suggestion.
