### ISSUE TITLE
[1.5.0] Mobile flow events (Android-only) find no phone

### ISSUE THREAD

**Issue by lubbertkramer** [athombv/homey-issues-dp#93]
**What is your Homey version (Settings → System)?**

1.5.0

**What did you try to achieve?**

Make use of the new phone cards introduced in 1.5 to trigger on incoming/outgoing call and phone gets connected/disconnected to power 

**What was the result?**

No phones found, are on the latest beta of the Android app
...

**What did you expect as result?**

Find and make use of my phone

**Any other remarks**

**Comment by jeroenvollenbrock** [comment]
Fixed with the new smartphone app
