### ISSUE TITLE
1.5.0 rename existing flow with a flow card, gives old flow name

### ISSUE THREAD

**Issue by robiebab** [athombv/homey-issues-dp#94]
**What is your Homey version (Settings → System)?**

1.5.0

**What did you try to achieve?**
change a name of a flow

*Please include detailed steps how we can reproduce the issue*
-create a flow with a flow card
-rename flow
-check flow again, and see the name in the flow card hasn't changed

**What was the result?**
flow card name stayed the same after changing the flow name
...

**What did you expect as result?**
that the name inside of the flow card was changed 
...

**Any other remarks**

...

**Comment by WeeJeWel** [comment]
Duplicate of https://github.com/athombv/homey/issues/330
