### ISSUE TITLE
1.5.0 can't see actual status (disable or enable) after using a flow  card

### ISSUE THREAD

**Issue by robiebab** [athombv/homey-issues-dp#96]
**What is your Homey version (Settings → System)?**

1.5.0

**What did you try to achieve?**
if i wanna disable or enable a flow using a flow card i don't see afterwards the actual status of the flow (disabled or enabled).
*Please include detailed steps how we can reproduce the issue*
create a new flow  met a flow card to disable a existing flow (flow example 1)
after running the new the new flow to disable flow example 1 i don't see the actual status

**What was the result?**
after running the new the new flow to disable flow example 1 i don't see the actual status
...

**What did you expect as result?**
that i see the actual status (disabled or enabled), and not need to click  to a other menu and return
...

**Any other remarks**

...

**Comment by jeroenvollenbrock** [comment]
We are no longer taking enhancement requests for the desktop interface through this issue tracker, due to it's incoming deprecation. Feel free to make one in the regular issue tracker though.
