### ISSUE TITLE
1.5.2 bug 51% relative dim card

### ISSUE THREAD

**Issue by robiebab** [athombv/homey-issues-dp#98]
**What is your Homey version (Settings → System)?**

1.5.2

**What did you try to achieve?**
if i dim my dimmer using the relative dim card to dim from to 51% to 50% it won't work

*Please include detailed steps how we can reproduce the issue*

set fibaro dimmer 2 to 51 %
create a new flow with a relative dim card.
set relative dim card to -1%
activate flow to use the relative dim card to set the fibaro dimmer 2 to 50%

**What was the result?**
it won't go down
...

**What did you expect as result?**
it will go down

...

**Any other remarks**

...

**Comment by WeeJeWel** [comment]
I cannot reproduce, so it must be a Fibaro Dimmer-specific issue.
