### ISSUE TITLE
[com.athom.homey2] Login is Case sensitive for email address.

### ISSUE THREAD

**Issue by Dijker** [athombv/homey-issues-dp#99]
**What is your Homey version (Settings → System)?**
App 0.4.0.104

**What did you try to achieve?**
Logon in App with Geurt@Dijker.nu like I do everywhere else (on Athom's Websites and almost all other sites.)

*Please include detailed steps how we can reproduce the issue*
Log on with Capitals in your email adres,

**What was the result?**
User Credentials are invalid. 

**What did you expect as result?**
The same as online where it works logging on with Capitals and everything is processed after a email.toLowerCase()

**Any other remarks**

**Comment by joachimroeleveld** [comment]
Fixed, thanks!
